// What the AI nations say, by situation, before it is flavoured by who is
// saying it. Every template is plain English; the {slots} are filled from the
// speaker's culture kit (NationVoices.ts):
//
//   {name}    the player the line is about or addressed to, shown under the
//             name the viewer knows them by (anonymized games stay so)
//   {hello} {yes} {no} {wow} {ugh} {thanks} {bye}   short words and
//             exclamations in the speaker's own language
//   {friend}  how they'd say "my friend"
//   {food}    a dish from home (plural or uncountable: "my {food}" reads right)
//   {place}   a place from home ("the Rhine", "Kyoto")
//
// Flavour text, like the tribe names: data, not UI, so not in en.json.

export const CHATTER_EVENTS = [
  "greeting",
  "idle",
  "attacked",
  "attacking",
  "allianceOffer",
  "allianceAccepted",
  "allianceRejected",
  "snubbed",
  "betrayed",
  "betrayer",
  "nuked",
  "nukeLaunch",
  "bigCity",
  "winning",
  "losing",
  "nearlyDead",
  "eliminated",
  "conquered",
  "donation",
  "targetRequest",
  "targetAck",
  "victory",
  "goodGame",
  "mention",
  "mentionGreet",
  "mentionAlly",
  "mentionThreat",
  "mentionThanks",
  "mentionSorry",
] as const;

export type ChatterEvent = (typeof CHATTER_EVENTS)[number];

export const TEMPLATES: Record<ChatterEvent, readonly string[]> = {
  greeting: [
    "{hello}, everyone! Good luck out there.",
    "{hello}! Who wants to be friends?",
    "{hello} from {place}!",
    "{hello}, neighbours. Let's keep it friendly. For now.",
    "Greetings from {place}! There's {food} if anyone's hungry.",
    "{hello}! May the best nation win. That's me, by the way.",
    "{hello}, everyone. Nice map. I'll take the good half.",
    "{hello}! I've packed {food} for the journey. Let's go.",
  ],
  idle: [
    "Anyone else hungry? I could go for some {food}.",
    "Lovely weather in {place} today.",
    "Just counting my troops. All of them. Again.",
    "Anyone want to trade? I have plenty of {food}.",
    "Wish you were all here in {place}.",
    "Quiet day. Too quiet.",
    "I'd tell you a joke about borders, but you'd have to cross a line to get it.",
    "If anyone needs me, I'll be in {place}.",
    "Remember, everyone: friends don't nuke friends.",
    "Who's winning? Asking for a friend.",
    "Fun fact: {food} is great before a battle. And after.",
    "My advisors say I should talk more. So: {hello}.",
    "Thinking about {food} again. It's a problem.",
    "Has anyone seen my spare warship? It was right here.",
    "Peace and quiet in {place}. I could get used to this.",
    "Everyone's so serious today. Have some {food}.",
    "I've been drawing my borders again. Bigger, this time.",
    "Someone build a railway to {place}. I'll wait.",
  ],
  attacked: [
    "{ugh} {name}, what did I ever do to you?",
    "{name}, get your troops off my border!",
    "You will not take {place} so easily, {name}.",
    "{ugh} An attack? I was just sitting down to some {food}.",
    "{name}, I was going to share my {food} with you. Not any more.",
    "Hands off {place}, {name}!",
    "{no}! Not today, {name}.",
    "So that's how it is, {name}? Fine. Bring it.",
    "Every inch of {place} will cost you, {name}.",
    "{name}, you'll regret this. Probably. Eventually.",
    "Rude, {name}. Very rude.",
    "I'm writing this down, {name}. In pen.",
    "Was that an attack, {name}? Bold of you.",
    "{ugh} {name}, knock first next time!",
  ],
  attacking: [
    "Sorry, {name}, nothing personal. Your land just looks so nice.",
    "{hello}, {name}! I've come to borrow some of your border.",
    "{name}, your land would look better with my flag on it.",
    "Ready or not, {name}, here I come!",
    "{name}, you have something I want. All of it.",
    "Don't take it personally, {name}. It's just strategy.",
    "Time to stretch my legs, {name}. Towards you.",
    "{wow} Fresh land, and it's {name}'s!",
    "My generals insist, {name}. Who am I to argue?",
    "Let's see what you're made of, {name}.",
    "Pack a lunch, {name}. Some {food}, maybe. This will take a while.",
  ],
  allianceOffer: [
    "{hello}, {name}! Friends? I'll bring the {food}.",
    "{name}, an alliance? The two of us, one enemy at a time.",
    "{name}, {friend}, shall we stand together?",
    "How about it, {name}? Allies? I'm much more fun as a friend.",
    "{name}, I've sent you an offer. Read it before you say no.",
    "Let's make a deal, {name}. You watch my back, I watch yours.",
    "{name}! Allies? There's room for both of us around {place}.",
  ],
  allianceAccepted: [
    "{wow} Allies it is, {name}!",
    "{yes}! Welcome, {name}, {friend}.",
    "A wise choice, {name}. Let's make some trouble together.",
    "{thanks}, {name}. Come by {place} some time, the {food} is on me.",
    "Allies! Don't make me regret this, {name}.",
    "{name} and me, together? The others should be worried.",
    "Deal, {name}. Shake on it?",
    "{wow} The two of us will go far, {name}.",
  ],
  allianceRejected: [
    "{no}, {name}. I don't trust you yet.",
    "Not now, {name}. Maybe after you prove yourself.",
    "{name}, I'll have to pass. Nothing personal.",
    "Ally with you, {name}? Ha! Good one.",
    "{no}. My advisors said no, and frankly so did I, {name}.",
    "Ask me again when you're bigger, {name}.",
  ],
  snubbed: [
    "{ugh} Fine, {name}. Your loss.",
    "Rejected? By {name}? I'll remember that.",
    "{name} said no. More {food} for me, then.",
    "All right, {name}. But the offer won't last for ever.",
    "{ugh} I thought we had something, {name}.",
  ],
  betrayed: [
    "{ugh} {name}! After everything we've been through?",
    "Traitor! I trusted you, {name}!",
    "{name}, you broke our alliance? The whole world saw that.",
    "I shared my {food} with you, {name}! My {food}!",
    "You will pay for this betrayal, {name}.",
    "Remember this moment, {name}. I certainly will.",
    "Everyone, mark my words: never trust {name}.",
    "{ugh} Backstabbed by {name}. Unbelievable.",
  ],
  betrayer: [
    "Sorry, {name}. It was a good alliance while it lasted.",
    "Nothing personal, {name}. Just business.",
    "{name}, you would have done the same. Probably.",
    "Our alliance has... ended early, {name}.",
    "{bye}, {name}. I'm going my own way.",
    "Don't look at me like that, {name}. You'd have done it first.",
  ],
  nuked: [
    "{ugh} A NUKE, {name}?! Have you lost your mind?",
    "{name}, you just nuked {place}! Have you no shame?",
    "My beautiful {place}! {name}, how could you?",
    "{ugh} {name}, the whole world saw that launch.",
    "That's it, {name}. No more Mr Nice Nation.",
    "Was that really necessary, {name}?!",
    "{name}, you'll answer for this.",
    "There goes my supply of {food}. Thanks a lot, {name}.",
  ],
  nukeLaunch: [
    "Incoming, {name}! Duck and cover!",
    "{name}, I'd look up if I were you.",
    "Special delivery for {name}!",
    "Sorry, {name}. You left me no choice.",
    "{name}, this one's for every border you crossed.",
    "Heads up, {name}. Way up.",
  ],
  bigCity: [
    "{wow} Look at my new city! Finest this side of {place}.",
    "A brand new city. The {food} there is excellent.",
    "{wow} Another city for the collection.",
    "My cities keep growing. Jealous, anyone?",
    "Come visit my new city! Bring an appetite for {food}.",
    "New city, new skyline. Not bad, right?",
  ],
  winning: [
    "Look at the map, everyone. Notice anything big?",
    "{wow} Biggest on the map! Who's next?",
    "From {place} to the horizon, it's all mine.",
    "Am I winning? I think I'm winning.",
    "Everyone, form an orderly line to surrender.",
    "Being on top is great. You should all try it some time.",
  ],
  losing: [
    "{ugh} This is not going well.",
    "I've lost half my land! Somebody help!",
    "{ugh} Where did all my land go?",
    "It's fine. Everything's fine. Mostly on fire, but fine.",
    "Things are rough, but at least I still have {food}.",
    "A tactical retreat. Very tactical. Extremely tactical.",
    "Any friends out there? Now would be a great time.",
  ],
  nearlyDead: [
    "{ugh} I'm down to my last few fields!",
    "Is this the end? At least I had {food}.",
    "Help! Anyone! I'll trade everything for a few troops!",
    "I'm not done yet! ...Am I?",
    "Tell my story, everyone. Tell them about {place}.",
    "Mercy! I'll throw in the {food}!",
  ],
  eliminated: [
    "{bye}, everyone. It was an honour.",
    "Remember {place}...",
    "{ugh} Well played, {name}. Well played.",
    "Gone, but my {food} lives on.",
    "{name} wins this round. Someone avenge me!",
    "Tell everyone I went down swinging.",
  ],
  conquered: [
    "Sorry, {name}. That's how it goes.",
    "{name} is no more. Who's next?",
    "{wow} Another one for the history books.",
    "GG, {name}. Better luck next game.",
    "Rest well, {name}. Your land is in good hands.",
  ],
  donation: [
    "{thanks}, {name}! You're a true friend.",
    "{wow} A gift! {thanks}, {name}!",
    "{name}, you shouldn't have! But I'm glad you did.",
    "{thanks}! I'll name a street in {place} after you, {name}.",
    "Very generous, {name}. The {food} is on me next time.",
    "{name}, this means a lot. {thanks}.",
  ],
  targetRequest: [
    "Everyone, {name} is getting too big. Let's fix that.",
    "Allies! Focus on {name}!",
    "{name} is the problem here. Let's solve it together.",
    "All together now: get {name}!",
    "Eyes on {name}, everyone.",
  ],
  targetAck: [
    "On it! {name} won't know what hit them.",
    "{yes}! Marching on {name}.",
    "Say no more. {name} it is.",
    "{name}? With pleasure.",
    "Consider it done. {name} is going down.",
  ],
  victory: [
    "{wow} Victory! Long live {place}!",
    "GG, everyone! The {food} is on me tonight.",
    "Victory! I'd like to thank my troops, my cities and my {food}.",
    "{wow} Did you see that? I won!",
    "Victory! Next time, maybe ally with me, everyone.",
  ],
  goodGame: [
    "Well played, {name}. GG.",
    "GG, {name}. I'll get you next time.",
    "{ugh} {name} wins. Rematch?",
    "Congratulations, {name}. You earned it.",
    "GG! {name}, come visit {place} some time.",
    "GG, everyone. Well played.",
    "{ugh} Rematch. Same time tomorrow?",
  ],
  mention: [
    "You called, {name}?",
    "{hello}, {name}! What can I do for you?",
    "{name}, I'm listening.",
    "Talking about me, {name}? I'm flattered.",
    "{name}, I heard my name. Good things, I hope.",
    "Yes, {name}? I'm a busy nation, you know.",
  ],
  mentionGreet: [
    "{hello}, {name}!",
    "{hello}, {name}! Nice to meet you.",
    "{hello}! Good to see you, {name}.",
    "{hello} to you too, {name}. Want some {food}?",
  ],
  mentionAlly: [
    "An alliance, {name}? Send the request and I'll think about it.",
    "Friends, {name}? Prove it.",
    "{name}, I'm always open to friends. Send an offer.",
    "Allies with {name}? Maybe. What's in it for me?",
  ],
  mentionThreat: [
    "Big words, {name}. Come and try.",
    "{ugh} Threats, {name}? I've heard scarier from my cat.",
    "{name}, you'd better have the troops to back that up.",
    "Ha! {name}, you and what army?",
    "Careful, {name}. {place} has a long memory.",
  ],
  mentionThanks: [
    "Any time, {name}.",
    "You're welcome, {name}!",
    "{name}, don't mention it. Really, don't. It's embarrassing.",
  ],
  mentionSorry: [
    "Apology accepted, {name}. For now.",
    "{name}, I'll forgive you. I won't forget, though.",
    "Sorry? Send gold, {name}. Then we'll talk.",
  ],
};
