// Which voice (NationVoices.ts) an AI nation speaks with, from the map it is
// on, its flag (the map's info.json `flag`: an ISO code, a region code like
// "RU-MOW" or "aus_nsw", or a named flag like "Cherokee Nation"), and its
// name. Anything unrecognised speaks the generic voice.

import { GameMapType } from "@openfront/engine-api/game/Maps.gen";

const g = (voice: string, ...flags: string[]): [string, string][] =>
  flags.map((f) => [f.toLowerCase(), voice]);

/** Exact flags, lower-cased. */
const FLAG_VOICES = new Map<string, string>([
  // Europe
  ...g(
    "german",
    "de",
    "east_germany",
    "west_germany",
    "German Confederation",
    "Holy Roman Empire",
    "prussia",
  ),
  ...g("alpine", "at", "ch", "li", "Habsburg Austria"),
  ...g(
    "french",
    "fr",
    "mc",
    "Franks",
    "1_Franks",
    "1_Occitania",
    "aquitaine",
    "armagnac",
    "avignon",
    "brittany",
    "burgundy",
    "normandy",
    "provence",
    "paris",
    "Corsica",
    "gp",
    "mq",
    "gf",
    "re",
    "pm",
    "bl",
    "mf",
    "pf",
    "nc",
    "wf",
    "tf",
    "Kingdom of Jerusalem",
    "County of Edessa",
    "Principality of Antioch",
    "County of Tripoli",
  ),
  ...g("lowlands", "nl", "be", "lu", "Flanders", "sr", "aw", "cw", "sx"),
  ...g(
    "british",
    "gb",
    "gb-eng",
    "gb-wls",
    "GB-CMA",
    "GB-LAN",
    "GB-Merseyside",
    "northern_ireland",
    "im",
    "je",
    "gg",
    "fk",
    "gs",
    "sh",
    "sh-ac",
    "io",
    "British Antarctic Territory",
    "bm",
    "pn",
  ),
  ...g("scottish", "gb-sct"),
  ...g("irish", "ie"),
  ...g(
    "italian",
    "it",
    "italy",
    "sm",
    "va",
    "venice",
    "TwoSicilies",
    "Kingdom of Sardinia",
    "Grand Duchy of Tuscany",
    "Duchy of Modena and Reggio",
    "Duchy of Parma",
    "PapalStates",
    "Sicily",
  ),
  ...g("maltese", "mt", "Order Of Malta"),
  ...g("roman", "SPQR"),
  ...g(
    "spanish",
    "es",
    "ad",
    "gi",
    "Crown Of Aragon",
    "castille",
    "leon",
    "navarre",
    "granada",
    "seville",
    "valencia",
    "majorca",
    "asturias",
    "cordoba",
    "es-an",
    "es-ga",
    "es-ce",
    "es-ml",
    "ic",
  ),
  ...g("catalan", "catalonia", "es-ct"),
  ...g("portuguese", "pt", "kingdom_of_portugal", "pt-azores"),
  ...g(
    "greek",
    "ha_ma",
    "gr",
    "cy",
    "Athens",
    "Sparta",
    "Byzantine Empire",
    "Macedonia",
    "Kingdom Of Cyprus",
  ),
  ...g(
    "turkish",
    "tr",
    "Sultanate Of Rum",
    "Seljuk Empire",
    "ottoman",
    "ottoman_empire",
  ),
  ...g("georgian", "ge", "Georgian SSR"),
  ...g("armenian", "am", "Armenian Kingdom Of Cilicia"),
  ...g("azerbaijani", "az", "Azerbaijan SSR"),
  ...g(
    "russian",
    "ru",
    "ussr",
    "Russian SSR",
    "Siberia",
    "Sakhalin",
    "Zheleznogorsk",
    "fareasternrepublic",
    "Chuvashia",
  ),
  ...g("ukrainian", "ua", "Ukrainian SSR", "crimea"),
  ...g("belarusian", "by", "Byelorussian SSR"),
  ...g("polish", "pl", "Danzig"),
  ...g("czechoslovak", "cz", "sk"),
  ...g("hungarian", "hu", "Kingdom of Hungary"),
  ...g("romanian", "ro", "md", "Moldavian SSR", "Transylvania"),
  ...g("bulgarian", "bg"),
  ...g(
    "balkan",
    "rs",
    "hr",
    "ba",
    "me",
    "si",
    "mk",
    "Republika Srpska",
    "Vojvodina",
  ),
  ...g("albanian", "al", "xk"),
  ...g(
    "scandinavian",
    "se",
    "no",
    "dk",
    "is",
    "fo",
    "ax",
    "sj",
    "Sweden Norway Union",
  ),
  ...g("finnish", "fi"),
  ...g(
    "baltic",
    "ee",
    "lv",
    "lt",
    "Setomaa",
    "Vorumaa",
    "Mulgimaa",
    "Noarootsi",
    "Votians",
  ),
  // Middle East and North Africa
  ...g(
    "gulf",
    "sa",
    "ae",
    "qa",
    "kw",
    "bh",
    "om",
    "ye",
    "Arabia",
    "Emirate of Asir",
    "Rashidi Emirate",
    "Sultanate of Nejd",
    "Kingdom of Yemen",
    "North yemen",
    "Aden State",
    "Emirate of Beihan",
    "Lower Aulaqi Sultanate",
    "Sultanate of Fadhli",
    "Sultanate of Lahej",
    "Sultanate of Lower Yafa",
  ),
  ...g(
    "levant",
    "lb",
    "sy",
    "jo",
    "iq",
    "ps",
    "Kingdom of Syria",
    "Kingdom of Iraq",
    "Second Republic of Iraq",
    "Abbasid Caliphate",
  ),
  ...g(
    "egyptian",
    "eg",
    "Kingdom of Egypt",
    "Fatimid Caliphate",
    "Ayyubid Dynasty",
  ),
  ...g(
    "maghreb",
    "ma",
    "dz",
    "tn",
    "ly",
    "mr",
    "eh",
    "Mauritania",
    "Rif",
    "hafsid",
    "marinid",
    "zayyanid",
  ),
  ...g("amazigh", "Amazigh flag"),
  ...g("israeli", "il"),
  ...g(
    "persian",
    "ir",
    "Persia",
    "Pahlavi Iran",
    "Achaemenid Empire",
    "Sassanid Empire",
  ),
  ...g("afghan", "af", "Emirate of Afghanistan"),
  // South and East Asia
  ...g("indian", "in", "Jammu and Kashmir", "Sikkim"),
  ...g("pakistani", "pk", "Azad Kashmir"),
  ...g("bangladeshi", "bd"),
  ...g("srilankan", "lk"),
  ...g("himalayan", "np", "bt", "tibet"),
  ...g(
    "chinese",
    "cn",
    "Qing Dynasty",
    "Republic of China",
    "Kuomintang_Emblem",
    "Flag_of_Taiping_Heavenly_Kingdom",
    "Ma_Clique_Flag",
    "Flag_of_Manchukuo",
  ),
  ...g("taiwanese", "tw"),
  ...g("cantonese", "hk", "mo", "Flag_of_Hong_Kong_(1959-1997)"),
  ...g("japanese", "jp", "Empire of Japan"),
  ...g("korean", "kr", "kp"),
  ...g(
    "steppe",
    "mn",
    "kz",
    "uz",
    "kg",
    "tm",
    "tj",
    "Kazakh SSR",
    "Kirghiz SSR",
    "Turkmen SSR",
    "Uzbek SSR",
    "Tajik SSR",
    "tannutuva",
    "Eastern_Turkistan_Flag",
  ),
  ...g("vietnamese", "vn", "South Vietnam"),
  ...g("thai", "th"),
  ...g("mainland_sea", "la", "kh", "mm", "Wa State"),
  ...g("malay", "id", "my", "bn", "sg", "tl", "Aceh", "Sarawak", "cx", "cc"),
  ...g("filipino", "ph"),
  // Oceania
  ...g("aussie", "au", "nf", "hm"),
  ...g("first_australians", "Australian Aboriginal Flag"),
  ...g("kiwi", "nz", "nz-chatham", "ck", "nu", "tk"),
  ...g("maori", "Maori flag"),
  ...g(
    "islands",
    "fj",
    "ws",
    "as",
    "to",
    "pg",
    "sb",
    "vu",
    "fm",
    "mh",
    "pw",
    "gu",
    "mp",
    "ki",
    "tv",
    "nr",
    "Hawaii",
  ),
  ...g(
    "indian_ocean",
    "sc",
    "mu",
    "mu-ro",
    "yt",
    "km",
    "Comoros Islamic Republic",
    "mv",
  ),
  ...g("malagasy", "mg", "Antankarana"),
  // Africa
  ...g("nigerian", "ng"),
  ...g("ghanaian", "gh"),
  ...g("west_african", "sl", "lr", "gm"),
  ...g("francophone_africa", "sn", "ci", "ml", "bf", "gn", "tg", "bj", "ne"),
  ...g("central_african", "cd", "cg", "cf", "td", "ga", "cm", "gq", "gq-an"),
  ...g("east_african", "ke", "tz", "ug", "rw", "bi", "Zanzibar"),
  ...g(
    "horn",
    "et",
    "er",
    "so",
    "dj",
    "Somaliland",
    "Puntland",
    "Ogaden",
    "Jubaland",
    "Ethiopian Empire",
    "Eritrea (Ethiopian)",
    "Adal Sultanate",
    "Beja",
  ),
  ...g("sudanese", "sd", "South Kordofan"),
  ...g("south_sudanese", "ss"),
  ...g(
    "southern_african",
    "za",
    "zw",
    "bw",
    "na",
    "ls",
    "sz",
    "zm",
    "mw",
    "Cape Town",
    "Good Hope",
  ),
  ...g("lusophone_africa", "ao", "mz", "cv", "gw", "st", "Mozambique PR"),
  // Americas
  ...g("american", "us", "um"),
  ...g(
    "canadian",
    "ca",
    "alberta",
    "britishcolumbia",
    "manitoba",
    "newbrunswick",
    "newfoundlandandlabrador",
    "Newfoundland",
    "novascotia",
    "ontario",
    "princeedwardisland",
    "saskatchewan",
    "northwestterritories",
    "Yukon",
    "Vancouver",
    "ca_nb",
    "ca_ns",
    "ca_pe",
  ),
  ...g("quebecois", "Quebec"),
  ...g(
    "arctic",
    "an_pe",
    "gl",
    "Nunavut",
    "Nunavik",
    "Sami flag",
    "aq",
    "polar_bears",
    "RU-SA",
    "RU-CHU",
    "RU-NEN",
    "RU-YAN",
  ),
  ...g("mexican", "mx", "Yucatan"),
  ...g("central_american", "gt", "hn", "sv", "ni", "cr", "pa"),
  ...g("caribbean_spanish", "cu", "do", "pr", "ve", "co"),
  ...g("andean", "pe", "bo", "ec", "cl", "Magallanes", "Santa Cruz"),
  ...g("rioplatense", "ar", "uy", "py", "Tierra del Fuego"),
  ...g("brazilian", "br", "bahia", "amazonas", "Para", "Sao Paulo"),
  ...g(
    "caribbean",
    "jm",
    "bs",
    "bb",
    "tt",
    "gd",
    "lc",
    "vc",
    "ag",
    "kn",
    "dm",
    "ky",
    "tc",
    "vg",
    "vi",
    "ai",
    "ms",
    "gy",
    "bz",
  ),
  ...g("haitian", "ht"),
  // US states and cities: by region
  ...g(
    "us_northeast",
    "Maine",
    "New_Hampshire",
    "Vermont",
    "Massachusetts",
    "Rhode_Island",
    "Connecticut",
    "New_York",
    "New_Jersey",
    "Pennsylvania",
    "Delaware",
    "Maryland",
    "Taunton",
    "Bedford",
    "Nantucket",
  ),
  ...g(
    "us_south",
    "Virginia",
    "West_Virginia",
    "North_Carolina",
    "South_Carolina",
    "Georgia_US",
    "Alabama",
    "Mississippi",
    "Tennessee",
    "Kentucky",
    "Arkansas",
    "Mobile",
  ),
  ...g("cajun", "Louisiana", "New Orleans", "Baton Rouge", "Acadiana"),
  ...g(
    "us_midwest",
    "Ohio",
    "Michigan",
    "Indiana",
    "Illinois",
    "Wisconsin",
    "Minnesota",
    "Iowa",
    "Missouri",
    "North_Dakota",
    "South_Dakota",
    "Nebraska",
    "Kansas",
  ),
  ...g(
    "us_southwest",
    "Texas",
    "Oklahoma",
    "New_Mexico",
    "Arizona",
    "Nevada",
    "Austin",
    "Houston",
    "San Antonio",
    "Corpus Christi",
  ),
  ...g(
    "us_west",
    "California",
    "Oregon",
    "Washington",
    "Idaho",
    "Montana",
    "Wyoming",
    "Colorado",
    "Utah",
    "Alaska",
  ),
  ...g("us_dc", "District_of_Columbia"),
  ...g(
    "florida",
    "Florida",
    "Jacksonville",
    "Tampa",
    "Miami",
    "Key West",
    "St Petersburg (US)",
  ),
  ...g("orlando", "Orlando"),
  ...g("apopka", "Apopka"),
  // Native nations
  ...g(
    "native",
    "Haudenosaunee",
    "Kanienkehaka",
    "Onyotaaka",
    "Gayogohono",
    "Onodowaga",
    "Skarure",
    "Penawahpskewi",
    "Peskotomuhkati",
    "Wolastoqiyik",
    "Alnobak",
    "Mi'kmaq",
    "Wabanaki",
    "Muhheconneok",
    "Schaghticoke",
    "Narragansett",
    "Mohegan",
    "Wopanaak",
    "Nipmuc",
    "Shinnecock",
    "Nanticoke",
    "Pamunkey",
    "Cheroenhaka",
    "Lenape",
    "Shawnee",
    "Mingo",
    "Wendat",
    "Myaamia",
    "Waayaahtanwa",
    "Piankashaw",
    "Odawa",
    "Bodewadmi",
    "Anishinaabe",
    "Mississauga",
    "Mamaceqtaw",
    "Cherokee Nation",
    "Iswa",
    "Mvskoke",
    "Mvskoke (Lower)",
    "Albaamaha",
    "Chickasaw",
    "Choctaw",
    "Seminole",
    "Miccosukee",
    "haida_flag",
  ),
  // Everything else
  ...g("pirate", "Republic of Pirates", "Black Flag"),
  ...g("north_pole", "santa_claus"),
  ...g(
    "space",
    "FlagOfMars",
    "custom/luna_monolith",
    "mars",
    "luna",
    "terra",
    "sol",
    "mercury",
    "venus",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "ceres",
    "eris",
    "eros",
    "haumea",
    "hygiea",
    "juno",
    "makemake",
    "orcus",
    "pallas",
    "quaoar",
    "salacia",
    "sedna",
    "vesta",
  ),
]);

// Regional flags by prefix: Germany's states, Spain's and France's regions,
// Ethiopia's, Britain's and Australia's, the Baikal map's.
const PREFIX_VOICES: [string, string][] = [
  ["de-", "german"],
  ["es-", "spanish"],
  ["fr-", "french"],
  ["et-", "horn"],
  ["gb-", "british"],
  ["aus_", "aussie"],
  ["ca_", "canadian"],
  ["bai_", "russian"],
  ["in-", "indian"],
  ["cn-", "chinese"],
  ["br-", "brazilian"],
  ["us-", "american"],
];

// Russia's federal subjects speak Russian, except the North Caucasus
// republics and the Turkic and Mongolic ones, which have voices of their own.
const RU_REGION_VOICES = new Map<string, string>([
  ...g(
    "steppe",
    "RU-TA",
    "RU-BA",
    "RU-BU",
    "RU-TY",
    "RU-KK",
    "RU-AL",
    "RU-KL",
    "RU-ALT",
  ),
  ...g(
    "generic",
    "RU-CE",
    "RU-IN",
    "RU-DA",
    "RU-KB",
    "RU-KC",
    "RU-AD",
    "RU-SE",
  ),
]);

// Britannia's early-medieval kingdoms ("1_Wessex"): the Irish and Scottish
// ones speak with today's voices, the rest from the mead hall.
const MEDIEVAL_VOICES = new Map<string, string>([
  ...g(
    "irish",
    "1_Airgialla",
    "1_Connacht",
    "1_Laigin",
    "1_Munster",
    "1_Northern Ui Neill",
    "1_Southern Ui Neill",
    "1_Ulaid",
  ),
  ...g("scottish", "1_Dalriata", "1_Fortriu", "1_Strathclyde"),
]);

/** Maps whose nations all share one local voice, whatever their flags. */
const MAP_VOICES = new Map<string, string>([
  [GameMapType.ApopkaDetailed, "apopka"],
  [GameMapType.Orlando, "orlando"],
  [GameMapType.OrlandoDetailed, "orlando"],
  [GameMapType.Aegean, "greek"],
  [GameMapType.Halkidiki, "greek"],
  [GameMapType.Lemnos, "greek"],
  [GameMapType.Hecatestrait, "native"],
  [GameMapType.WashingtonDCDetailed, "us_dc"],
  [GameMapType.Mars, "space"],
  [GameMapType.Luna, "space"],
  [GameMapType.Titan, "space"],
  [GameMapType.Pluto, "space"],
  [GameMapType.Sol, "space"],
  [GameMapType.MilkyWay, "space"],
]);

const COLONIAL_MAPS = new Set<string>([
  GameMapType.ThirteenColonies,
  GameMapType.ThirteenColoniesDetailed,
]);

const COLONY_FLAGS = new Set(
  [
    "New_Hampshire",
    "Massachusetts (Naval)",
    "Massachusetts",
    "Rhode_Island",
    "Connecticut",
    "New_York",
    "New_Jersey",
    "Pennsylvania",
    "Delaware",
    "Maryland",
    "Virginia",
    "North_Carolina",
    "Moultrie Flag",
    "South_Carolina",
    "Georgia (1775)",
  ].map((f) => f.toLowerCase()),
);

const NAME_VOICES: [RegExp, string][] = [
  [/apopka|wekiwa|zellwood|errol estates/i, "apopka"],
  [/\b(orlando|lake eola|ucf|lake nona)\b/i, "orlando"],
  [
    /cherokee|tsalagi|seminole|haudenosaunee|mohawk|oneida|lenape|shawnee|anishinaabe|ojibwe|mvskoke|choctaw|chickasaw|wampanoag|abenaki|mi'kmaq|wabanaki/i,
    "native",
  ],
  [
    /\b(unami|unalachtigo|munsee|mannahatta|montaukett|unkechaug|shinnecock|weckquaesgeek|siwanoy|canarsie|rockaway|kwakwaka'wakw|coast salish|nuu-chah-nulth)\b/i,
    "native",
  ],
  [/\b(kuwait|oman|muscat|trucial|qatar|bahrain)\b/i, "gulf"],
  [/pirate/i, "pirate"],
];

/**
 * The voice an AI nation speaks with. `flag` is the nation's flag code as the
 * map's info.json gives it (null for none); `map` the game's map.
 */
export function voiceFor(
  name: string,
  flag: string | null,
  map: GameMapType | string,
): string {
  const f = (flag ?? "").toLowerCase();
  if (FLAG_VOICES.get(f) === "native") return "native";
  // Apopka is Apopka on any map.
  if (/apopka/i.test(name) || f === "apopka") return "apopka";
  const mapVoice = MAP_VOICES.get(map);
  if (mapVoice !== undefined) return mapVoice;
  if (COLONIAL_MAPS.has(map) && COLONY_FLAGS.has(f)) return "colonial";

  const exact = FLAG_VOICES.get(f);
  if (exact !== undefined) return exact;
  if (f.startsWith("ru-")) return RU_REGION_VOICES.get(f) ?? "russian";
  if (f.startsWith("1_")) return MEDIEVAL_VOICES.get(f) ?? "medieval";
  for (const [prefix, voice] of PREFIX_VOICES) {
    if (f.startsWith(prefix)) return voice;
  }
  for (const [re, voice] of NAME_VOICES) {
    if (re.test(name)) return voice;
  }
  return "generic";
}
