// How each kind of AI nation talks: a friendly nod to where it is from.
//
// The rules these follow (the owner was promised them):
//  - English, with a few real words of the nation's own language: greetings,
//    thanks, everyday exclamations. Spelled as the language spells them,
//    never a fake accent written phonetically.
//  - Food, places, sayings and history from home, the kind locals are proud
//    of. No slurs and no demeaning stereotypes, of anyone.
//  - Native nations speak plain, dignified English about their own councils,
//    rivers, crops and treaties: no "movie Indian" talk, no invented words.
//
// A kit fills the {slots} of the shared templates (ChatterTemplates.ts);
// `lines` are whole lines of the group's own, used alongside them. Any slot
// a kit leaves out falls back to the generic kit. Flavour text, like the
// tribe names: data, not UI, so it is not in en.json.

import { ChatterEvent } from "./ChatterTemplates";

export interface VoiceKit {
  hello?: readonly string[];
  yes?: readonly string[];
  no?: readonly string[];
  wow?: readonly string[];
  ugh?: readonly string[];
  thanks?: readonly string[];
  bye?: readonly string[];
  friend?: readonly string[];
  food?: readonly string[];
  place?: readonly string[];
  lines?: Partial<Record<ChatterEvent, readonly string[]>>;
}

export const GENERIC_KIT: Required<Omit<VoiceKit, "lines">> = {
  hello: ["Hello", "Hi there", "Greetings"],
  yes: ["Yes", "Sure", "Of course"],
  no: ["No", "No way", "Not a chance"],
  wow: ["Excellent!", "Wonderful!", "Great!", "Fantastic!"],
  ugh: ["Oh no!", "Ugh!", "Unbelievable!", "Oh, come on!"],
  thanks: ["Thanks", "Thank you", "Much appreciated"],
  bye: ["Goodbye", "Farewell", "See you"],
  friend: ["my friend"],
  food: ["fresh bread", "hot soup", "cake", "tea", "dumplings"],
  place: ["my capital", "the homeland", "my heartland", "the old town"],
};

export const VOICES: Record<string, VoiceKit> = {
  generic: {
    lines: {
      idle: [
        "Somebody should really draw these borders straighter.",
        "I'm not saying I'm the best nation. I'm just thinking it.",
      ],
    },
  },

  // ---------------------------------------------------------------- Europe
  german: {
    hello: ["Hallo", "Guten Tag", "Servus", "Moin"],
    yes: ["Ja", "Genau", "Natürlich", "Klar"],
    no: ["Nein", "Auf keinen Fall"],
    wow: ["Wunderbar!", "Super!", "Sehr gut!", "Toll!"],
    ugh: ["Ach nein!", "Mist!", "Donnerwetter!", "So ein Quatsch!"],
    thanks: ["Danke", "Danke schön", "Vielen Dank"],
    bye: ["Tschüss", "Auf Wiedersehen", "Bis bald"],
    friend: ["mein Freund"],
    food: [
      "pretzels",
      "Black Forest cake",
      "bratwurst",
      "apple strudel",
      "Spätzle",
      "currywurst",
    ],
    place: [
      "the Rhine",
      "Bavaria",
      "the Black Forest",
      "Berlin",
      "Hamburg",
      "the Moselle valley",
    ],
    lines: {
      idle: [
        "As we say: Ende gut, alles gut. All's well that ends well.",
        "My invasion plan is in a folder. The folder has tabs. Colour-coded.",
        "Ordnung muss sein. There must be order, especially on my borders.",
        "Who wants Kaffee und Kuchen? It's three o'clock, after all.",
        "I've built a motorway to the front. No speed limit.",
      ],
      attacked: [
        "Ach nein! My Black Forest cake is still in the oven!",
        "{name}, this was not on the schedule!",
      ],
      allianceAccepted: ["Wunderbar! Prost, {name}, to our alliance!"],
      betrayed: ["{name}, I had filed the alliance paperwork in triplicate!"],
      victory: ["Wunderbar! The beer gardens are open, everyone!"],
    },
  },
  alpine: {
    hello: ["Grüezi", "Servus", "Grüß Gott", "Hoi"],
    yes: ["Ja", "Genau", "Gern"],
    no: ["Nein", "Sicher nicht"],
    wow: ["Super!", "Wunderbar!", "Leiwand!", "Herrlich!"],
    ugh: ["Oje!", "Ach du lieber!", "Hoppla!"],
    thanks: ["Danke", "Merci vielmals", "Danke vielmals"],
    bye: ["Ciao", "Uf Wiederluege", "Baba"],
    friend: ["mein Freund"],
    food: [
      "fondue",
      "Rösti",
      "Sachertorte",
      "Swiss chocolate",
      "Wiener schnitzel",
      "Kaiserschmarrn",
    ],
    place: [
      "the Alps",
      "the Matterhorn",
      "Vienna",
      "Lake Geneva",
      "Salzburg",
      "the Jungfrau",
    ],
    lines: {
      idle: [
        "I'm normally neutral. Normally.",
        "Anyone for a waltz? The orchestra is warming up.",
        "My cheese has holes in it. My defences do not.",
        "Fresh mountain air. You should try it instead of fighting.",
      ],
      attacked: [
        "{name}, I was being neutral! You've ruined it!",
        "{ugh} You've tracked mud all over my nice clean Alps, {name}.",
      ],
      donation: ["{thanks}, {name}! It goes straight into my bank vault."],
    },
  },
  french: {
    hello: ["Bonjour", "Salut", "Coucou"],
    yes: ["Oui", "Bien sûr", "D'accord"],
    no: ["Non", "Jamais", "Pas question"],
    wow: ["Magnifique!", "Formidable!", "Ooh là là!", "C'est génial!"],
    ugh: ["Sacré bleu!", "Zut alors!", "Mon Dieu!", "Quelle horreur!"],
    thanks: ["Merci", "Merci beaucoup"],
    bye: ["Au revoir", "À bientôt", "Adieu"],
    friend: ["mon ami"],
    food: [
      "croissants",
      "baguettes",
      "camembert",
      "crêpes",
      "macarons",
      "coq au vin",
      "ratatouille",
    ],
    place: [
      "Paris",
      "Provence",
      "the Loire",
      "Normandy",
      "the Riviera",
      "Bordeaux",
    ],
    lines: {
      idle: [
        "C'est la vie, everyone. That's life.",
        "Nobody touches my boulangerie. Nobody.",
        "Who wants a picnic by the Seine? Bring cheese. Lots of cheese.",
        "I have declared a two-hour lunch. Please do not invade until three.",
      ],
      attacked: [
        "Sacré bleu! {name}, you've interrupted my lunch!",
        "{name}! Not the vineyards! Anything but the vineyards!",
      ],
      victory: ["Magnifique! Champagne for everyone!"],
      allianceAccepted: ["Formidable! Vive l'amitié, {name}!"],
    },
  },
  lowlands: {
    hello: ["Hallo", "Hoi", "Goedendag", "Dag"],
    yes: ["Ja", "Zeker", "Prima"],
    no: ["Nee", "Echt niet"],
    wow: ["Lekker!", "Gezellig!", "Prachtig!", "Top!"],
    ugh: ["Potverdorie!", "Jeetje!", "Oei!", "Verdorie!"],
    thanks: ["Dank je wel", "Bedankt", "Merci"],
    bye: ["Doei", "Tot ziens", "Salut"],
    friend: ["vriend"],
    food: [
      "stroopwafels",
      "Gouda",
      "Belgian waffles",
      "frites with mayo",
      "bitterballen",
      "Belgian chocolate",
    ],
    place: [
      "Amsterdam",
      "the canals",
      "the tulip fields",
      "Antwerp",
      "Brussels",
      "the dikes",
    ],
    lines: {
      idle: [
        "I took this land from the sea. I can take some from you too.",
        "Anyone seen my bicycle? Never mind, I have eleven more.",
        "The windmills are turning nicely today. Gezellig.",
      ],
      attacked: [
        "{name}! I'll open the dikes, I swear it!",
        "{ugh} You rode straight through my tulips, {name}!",
      ],
    },
  },
  british: {
    hello: ["Hello", "Hiya", "Morning", "Alright"],
    yes: ["Right", "Indeed", "Quite", "Of course"],
    no: ["Absolutely not", "Not a chance", "I think not"],
    wow: ["Brilliant!", "Splendid!", "Jolly good!", "Lovely!", "Smashing!"],
    ugh: ["Blimey!", "Good grief!", "Oh, bother!", "Crikey!", "Oh, honestly!"],
    thanks: ["Cheers", "Ta", "Much obliged", "Thanks ever so"],
    bye: ["Cheerio", "Ta-ra", "Toodle-oo"],
    friend: ["mate", "old chap"],
    food: [
      "tea",
      "fish and chips",
      "scones",
      "Sunday roast",
      "crumpets",
      "beans on toast",
      "Welsh cakes",
    ],
    place: [
      "London",
      "the Thames",
      "the Cotswolds",
      "Yorkshire",
      "Snowdonia",
      "the Lake District",
    ],
    lines: {
      idle: [
        "Anyone fancy a cuppa? Kettle's on.",
        "Lovely day for it. Bit of drizzle, but lovely.",
        "Keep calm and carry on, everyone.",
        "I've formed an orderly queue at the border. Please respect it.",
        "Rain again. Perfect weather for an invasion, really.",
      ],
      attacked: [
        "I say, {name}! That's simply not cricket!",
        "{name}, I was in the middle of my tea!",
      ],
      betrayed: ["Frightfully poor form, {name}. Frightfully poor."],
      donation: ["Oh, you shouldn't have, {name}! Cheers ever so."],
    },
  },
  scottish: {
    hello: ["Hello", "Aye", "Hiya"],
    yes: ["Aye", "Aye, nae bother"],
    no: ["Naw", "Nae chance"],
    wow: ["Braw!", "Pure dead brilliant!", "Smashing!"],
    ugh: ["Och!", "Jings!", "Crivens!", "Och, away!"],
    thanks: ["Cheers", "Ta", "Thanks a lot"],
    bye: ["Cheerio", "See you after", "Haste ye back"],
    friend: ["pal", "my wee pal"],
    food: ["haggis", "shortbread", "tablet", "cranachan", "Cullen skink"],
    place: [
      "the Highlands",
      "Loch Ness",
      "Edinburgh",
      "the Isle of Skye",
      "the Clyde",
      "Ben Nevis",
    ],
    lines: {
      idle: [
        "Four seasons in one day up here. Bring a jacket.",
        "Anyone seen the monster in the loch? No? Me neither.",
        "Lang may yer lum reek, everyone. Long may your chimney smoke.",
      ],
      attacked: [
        "Och, {name}! You will not get past the Highlands that easily!",
      ],
    },
  },
  irish: {
    hello: ["Dia duit", "Howya", "Hello"],
    yes: ["Grand", "Sure look", "Go on"],
    no: ["Ah no", "Not at all"],
    wow: ["Deadly!", "Savage!", "Grand job!", "Sláinte!"],
    ugh: ["Ah, stop!", "Would you stop!", "For the love of God!"],
    thanks: ["Go raibh maith agat", "Thanks a million", "Cheers"],
    bye: ["Slán", "See ya", "Mind yourself"],
    friend: ["my friend", "a chara"],
    food: [
      "soda bread",
      "Irish stew",
      "colcannon",
      "boxty",
      "a full Irish",
      "brown bread",
    ],
    place: [
      "Dublin",
      "the Cliffs of Moher",
      "Galway",
      "the Shannon",
      "Connemara",
      "Cork",
    ],
    lines: {
      idle: [
        "The craic is mighty today, isn't it?",
        "Ah sure, it'll be grand. It's always grand.",
        "Is it raining where you are? It's raining here. Grand.",
      ],
      attacked: ["Would you ever get out of my fields, {name}?"],
      allianceAccepted: ["Sláinte, {name}! To friends!"],
    },
  },
  italian: {
    hello: ["Ciao", "Buongiorno", "Salve"],
    yes: ["Sì", "Certo", "Va bene"],
    no: ["No", "Assolutamente no", "Neanche per sogno"],
    wow: ["Bellissimo!", "Fantastico!", "Perfetto!", "Che bello!"],
    ugh: ["Mamma mia!", "Che disastro!", "Accidenti!", "Uffa!"],
    thanks: ["Grazie", "Grazie mille"],
    bye: ["Ciao", "Arrivederci", "A presto"],
    friend: ["amico mio"],
    food: [
      "pasta",
      "pizza",
      "gelato",
      "risotto",
      "tiramisù",
      "espresso",
      "Parmigiano",
    ],
    place: [
      "Rome",
      "Venice",
      "Tuscany",
      "Sicily",
      "Naples",
      "the Amalfi coast",
    ],
    lines: {
      idle: [
        "Who put pineapple on the pizza? Confess.",
        "Rome wasn't built in a day. My empire might be, though.",
        "Espresso break, everyone. Five minutes. No invading.",
        "Dolce far niente. The sweetness of doing nothing.",
      ],
      attacked: [
        "Mamma mia, {name}! Not while the pasta is boiling!",
        "{name}! You'll break my grandmother's heart!",
      ],
      victory: ["Bellissimo! Gelato for everyone!"],
    },
  },
  maltese: {
    hello: ["Bonġu", "Merħba", "Hello"],
    thanks: ["Grazzi", "Grazzi ħafna"],
    wow: ["Prosit!", "Mela!", "Bravu!"],
    bye: ["Saħħa", "Ċaw"],
    food: ["pastizzi", "rabbit stew", "ftira", "imqaret"],
    place: ["Valletta", "Gozo", "the Grand Harbour", "Mdina"],
  },
  roman: {
    hello: ["Ave", "Salve"],
    yes: ["Ita", "Certe"],
    no: ["Minime", "Non"],
    wow: ["Euge!", "Optime!", "Io triumphe!"],
    ugh: ["Pro di immortales!", "Eheu!", "Edepol!"],
    thanks: ["Gratias", "Gratias tibi ago"],
    bye: ["Vale", "Valete"],
    friend: ["amice"],
    food: ["olives", "garum", "honey cakes", "spiced wine", "flatbread"],
    place: ["the Forum", "the Tiber", "the Seven Hills", "the Via Appia"],
    lines: {
      idle: [
        "Alea iacta est. The die is cast.",
        "Carpe diem, everyone. Seize the day. Also your neighbour's land.",
        "All roads lead to my capital. I built them that way.",
        "Bread and circuses for my citizens! Mostly bread.",
      ],
      victory: ["Veni, vidi, vici. I came, I saw, I conquered."],
      attacked: ["{name}! The Senate shall hear of this!"],
    },
  },
  spanish: {
    hello: ["Hola", "Buenas", "Buenos días"],
    yes: ["Sí", "Claro", "Vale"],
    no: ["No", "Ni hablar", "Para nada"],
    wow: ["¡Olé!", "¡Qué bien!", "¡Genial!", "¡Estupendo!"],
    ugh: ["¡Madre mía!", "¡Ay, caramba!", "¡Qué desastre!", "¡Vaya!"],
    thanks: ["Gracias", "Muchas gracias"],
    bye: ["Adiós", "Hasta luego", "Hasta pronto"],
    friend: ["amigo"],
    food: [
      "paella",
      "tapas",
      "churros",
      "jamón",
      "tortilla española",
      "gazpacho",
    ],
    place: [
      "Madrid",
      "Barcelona",
      "Andalusia",
      "the Pyrenees",
      "Seville",
      "Valencia",
    ],
    lines: {
      idle: [
        "Dinner is at ten. Anyone who attacks before then is very rude.",
        "The flamenco starts at midnight. Come, clap along.",
        "Tapas, anyone? A little bit of everything.",
      ],
      attacked: ["¡Madre mía, {name}! In the middle of the tapas?"],
      victory: ["¡Olé! Fiesta in the plaza tonight!"],
    },
  },
  catalan: {
    hello: ["Bon dia", "Hola"],
    yes: ["Sí", "És clar"],
    wow: ["Molt bé!", "Que bonic!"],
    ugh: ["Mare meva!", "Ostres!"],
    thanks: ["Gràcies", "Moltes gràcies"],
    bye: ["Adéu", "Fins aviat"],
    food: ["pa amb tomàquet", "crema catalana", "calçots", "fideuà"],
    place: ["Barcelona", "Montserrat", "the Costa Brava", "Girona"],
    lines: {
      idle: ["Our human towers are taller than your castles."],
    },
  },
  portuguese: {
    hello: ["Olá", "Bom dia", "Boa tarde"],
    yes: ["Sim", "Claro"],
    no: ["Não", "Nem pensar"],
    wow: ["Fixe!", "Que maravilha!", "Espetacular!", "Muito bem!"],
    ugh: ["Ai, meu Deus!", "Que chatice!", "Caramba!"],
    thanks: ["Obrigado", "Muito obrigado"],
    bye: ["Adeus", "Até logo", "Tchau"],
    friend: ["meu amigo"],
    food: [
      "pastéis de nata",
      "bacalhau",
      "grilled sardines",
      "francesinhas",
      "port wine",
    ],
    place: ["Lisbon", "Porto", "the Algarve", "the Douro", "Sintra"],
    lines: {
      idle: [
        "I've sailed around the world before, you know. A map like this is nothing.",
        "Fado is playing in the harbour. A little sad, but beautiful.",
      ],
      attacked: ["{name}! I discovered half the world, I'll defend this bit!"],
    },
  },
  greek: {
    hello: ["Yassou", "Kalimera", "Yassas"],
    yes: ["Ne", "Vevaia", "Entaxei"],
    no: ["Ochi", "Kamia schesi"],
    wow: ["Opa!", "Bravo!", "Teleia!", "Ti oraia!"],
    ugh: ["Po po po!", "Ela tora!", "Ti les?!"],
    thanks: ["Efcharistó", "Efcharistó polý"],
    bye: ["Yassou", "Antío", "Kalinychta"],
    friend: ["file mou"],
    food: ["souvlaki", "feta", "baklava", "moussaka", "olives", "spanakopita"],
    place: [
      "Athens",
      "the Aegean",
      "Santorini",
      "Olympus",
      "Crete",
      "the Acropolis",
    ],
    lines: {
      idle: [
        "We invented democracy. Shall we vote on who I attack next?",
        "Know thyself, as the philosophers said. I know myself: hungry.",
        "Opa! Who broke a plate? That's good luck, actually.",
      ],
      attacked: ["{name}, I've seen better tactics in a Spartan nursery!"],
      victory: ["Opa! A laurel wreath for me, please!"],
    },
  },
  turkish: {
    hello: ["Merhaba", "Selam", "İyi günler"],
    yes: ["Evet", "Tabii", "Tamam"],
    no: ["Hayır", "Asla", "Olmaz"],
    wow: ["Harika!", "Süper!", "Çok güzel!", "Helal olsun!"],
    ugh: ["Eyvah!", "Aman!", "Yok artık!", "Hay aksi!"],
    thanks: ["Teşekkürler", "Sağ ol", "Çok teşekkürler"],
    bye: ["Hoşça kal", "Görüşürüz"],
    friend: ["kardeşim", "arkadaşım"],
    food: [
      "baklava",
      "döner",
      "Turkish delight",
      "simit",
      "Turkish tea",
      "köfte",
    ],
    place: [
      "Istanbul",
      "the Bosphorus",
      "Anatolia",
      "Cappadocia",
      "the Black Sea coast",
    ],
    lines: {
      idle: [
        "Tea is brewing. Two sugars? Sit, sit.",
        "Istanbul has one foot in Europe and one in Asia. I could do the splits on this map.",
      ],
      attacked: ["{name}! I just poured the tea!"],
    },
  },
  georgian: {
    hello: ["Gamarjoba", "Hello"],
    thanks: ["Madloba", "Didi madloba"],
    wow: ["Gaumarjos!", "Super!"],
    bye: ["Nakhvamdis"],
    food: ["khachapuri", "khinkali", "churchkhela", "Georgian wine"],
    place: ["Tbilisi", "the Caucasus", "Kakheti", "Svaneti"],
    lines: {
      idle: ["A Georgian feast has twenty toasts. I'm on toast number nine."],
    },
  },
  armenian: {
    hello: ["Barev", "Barev dzez"],
    thanks: ["Shnorhakalutyun", "Merci"],
    wow: ["Hrashali!", "Shat lav!"],
    bye: ["Tstesutyun"],
    food: ["lavash", "dolma", "khorovats", "apricots", "gata"],
    place: ["Yerevan", "Lake Sevan", "the Ararat valley", "Dilijan"],
  },
  azerbaijani: {
    hello: ["Salam", "Xoş gəldiniz"],
    thanks: ["Sağ ol", "Təşəkkür edirəm"],
    wow: ["Əla!", "Super!"],
    bye: ["Sağ ol", "Görüşərik"],
    food: ["plov", "dolma", "qutab", "pakhlava", "black tea"],
    place: ["Baku", "the Caspian shore", "Sheki", "the Caucasus"],
  },
  russian: {
    hello: ["Privet", "Zdravstvuyte", "Dobryy den"],
    yes: ["Da", "Konechno", "Khorosho"],
    no: ["Nyet", "Ni za chto"],
    wow: ["Otlichno!", "Molodets!", "Krasota!", "Super!"],
    ugh: ["Oy!", "Bozhe moy!", "Uzhas!", "Nu vot!"],
    thanks: ["Spasibo", "Bolshoye spasibo"],
    bye: ["Poka", "Do svidaniya"],
    friend: ["moy drug"],
    food: [
      "borscht",
      "pelmeni",
      "blini",
      "pirozhki",
      "hot tea from the samovar",
      "Olivier salad",
    ],
    place: [
      "the Volga",
      "Siberia",
      "Moscow",
      "the Urals",
      "Lake Baikal",
      "St Petersburg",
    ],
    lines: {
      idle: [
        "Winter is coming. In Siberia, it never really left.",
        "The samovar is hot. Who wants tea?",
        "My land is so big it has eleven time zones. Good morning, good night, everyone.",
      ],
      attacked: ["{name}, have you seen how big I am? Good luck."],
    },
  },
  ukrainian: {
    hello: ["Pryvit", "Dobryi den", "Vitayu"],
    yes: ["Tak", "Zvychaino"],
    no: ["Ni", "Nizashcho"],
    wow: ["Chudovo!", "Klas!", "Super!", "Molodets!"],
    ugh: ["Oi!", "Bozhe!", "Lykho!"],
    thanks: ["Diakuiu", "Duzhe diakuiu"],
    bye: ["Buvai", "Do pobachennia"],
    friend: ["druzhe"],
    food: ["varenyky", "borscht", "pampushky", "holubtsi", "syrnyky"],
    place: [
      "the Dnipro",
      "Kyiv",
      "the Carpathians",
      "Odesa",
      "Lviv",
      "the sunflower fields",
    ],
    lines: {
      idle: [
        "The sunflowers are tall this year. Good sign.",
        "Lviv coffee or Odesa sea air? I can't choose.",
      ],
    },
  },
  belarusian: {
    hello: ["Pryvitannie", "Dobry dzien"],
    thanks: ["Dziakuj"],
    wow: ["Cudoŭna!", "Super!"],
    bye: ["Da pabačennia"],
    food: ["draniki", "machanka", "kalduny", "babka"],
    place: ["Minsk", "the Belovezha forest", "the Neman", "Polesia"],
  },
  polish: {
    hello: ["Cześć", "Dzień dobry", "Siema"],
    yes: ["Tak", "Oczywiście"],
    no: ["Nie", "W żadnym wypadku"],
    wow: ["Super!", "Świetnie!", "Ekstra!", "Rewelacja!"],
    ugh: ["O rany!", "Kurczę!", "Jejku!", "Matko!"],
    thanks: ["Dziękuję", "Dzięki"],
    bye: ["Na razie", "Do widzenia", "Cześć"],
    friend: ["przyjacielu"],
    food: ["pierogi", "bigos", "kiełbasa", "pączki", "żurek", "sernik"],
    place: ["the Vistula", "Kraków", "Warsaw", "the Tatras", "Gdańsk"],
    lines: {
      idle: [
        "Grandma made too many pierogi again. Come and get some.",
        "Not my circus, not my monkeys, as we say. Your war, not mine. For now.",
      ],
      attacked: ["{name}! You'd better not touch Grandma's pierogi!"],
    },
  },
  czechoslovak: {
    hello: ["Ahoj", "Dobrý den", "Nazdar"],
    yes: ["Jo", "Ano", "Áno"],
    no: ["Ne", "Nie"],
    wow: ["Paráda!", "Super!", "Bezva!"],
    ugh: ["Jejda!", "Ach jo!", "No teda!"],
    thanks: ["Děkuji", "Díky", "Ďakujem"],
    bye: ["Čau", "Na shledanou", "Dovidenia"],
    friend: ["kamaráde"],
    food: [
      "svíčková",
      "trdelník",
      "dumplings",
      "bryndzové halušky",
      "kolaches",
    ],
    place: ["Prague", "the Vltava", "the Tatras", "Bratislava", "Bohemia"],
    lines: {
      idle: [
        "Prague is a hundred spires and one very long queue for the bridge.",
      ],
    },
  },
  hungarian: {
    hello: ["Szia", "Jó napot", "Sziasztok"],
    yes: ["Igen", "Persze"],
    no: ["Nem", "Szó sem lehet róla"],
    wow: ["Szuper!", "Nagyszerű!", "Hű, de jó!"],
    ugh: ["Jaj!", "Te jó ég!", "A mindenit!"],
    thanks: ["Köszönöm", "Köszi"],
    bye: ["Viszlát", "Szia"],
    friend: ["barátom"],
    food: [
      "goulash",
      "lángos",
      "chimney cake",
      "paprika chicken",
      "Dobos torte",
    ],
    place: [
      "Budapest",
      "the Danube",
      "Lake Balaton",
      "the Great Plain",
      "Tokaj",
    ],
    lines: {
      idle: ["We invented the Rubik's Cube. This map is easier."],
    },
  },
  romanian: {
    hello: ["Bună", "Salut", "Bună ziua"],
    yes: ["Da", "Sigur"],
    no: ["Nu", "Nici gând"],
    wow: ["Super!", "Minunat!", "Bravo!"],
    ugh: ["Vai de mine!", "Of!", "Doamne!"],
    thanks: ["Mulțumesc", "Mersi"],
    bye: ["La revedere", "Pa"],
    friend: ["prietene"],
    food: ["sarmale", "mămăligă", "mici", "papanași", "cozonac"],
    place: [
      "the Carpathians",
      "the Danube Delta",
      "Bucharest",
      "Transylvania",
      "the Black Sea",
    ],
    lines: {
      idle: [
        "The Carpathians are lovely this time of year. Every time of year.",
      ],
    },
  },
  bulgarian: {
    hello: ["Zdravei", "Dobar den"],
    yes: ["Da"],
    no: ["Ne"],
    wow: ["Super!", "Bravo!", "Chudesno!"],
    ugh: ["Le le!", "Mamo mila!", "Abe!"],
    thanks: ["Blagodarya", "Mersi"],
    bye: ["Dovizhdane", "Chao"],
    friend: ["priyatelyu"],
    food: ["banitsa", "shopska salad", "yoghurt", "kebapche", "lyutenitsa"],
    place: [
      "Sofia",
      "the Rila mountains",
      "the Black Sea coast",
      "the Valley of Roses",
      "Plovdiv",
    ],
    lines: {
      idle: [
        "Here we shake our heads for yes and nod for no. Good luck reading my plans.",
      ],
    },
  },
  balkan: {
    hello: ["Zdravo", "Ćao", "Bok", "Pozdrav"],
    yes: ["Da", "Naravno", "Može"],
    no: ["Ne", "Nema šanse"],
    wow: ["Bravo!", "Super!", "Odlično!", "Ajde!"],
    ugh: ["Joj!", "Ajme!", "Bre!", "Ma daj!"],
    thanks: ["Hvala", "Hvala puno"],
    bye: ["Ćao", "Vidimo se", "Doviđenja"],
    friend: ["brate", "prijatelju"],
    food: ["ćevapi", "burek", "ajvar", "sarma", "strong coffee", "palačinke"],
    place: [
      "the Adriatic",
      "the Danube",
      "Dubrovnik",
      "the Dinaric Alps",
      "Lake Ohrid",
      "Kotor",
    ],
    lines: {
      idle: [
        "Coffee here takes two hours. That's the point.",
        "Ajde, who's grilling? I'll bring the ćevapi.",
      ],
    },
  },
  albanian: {
    hello: ["Përshëndetje", "Tungjatjeta", "Ç'kemi"],
    yes: ["Po", "Sigurisht"],
    no: ["Jo"],
    wow: ["Shumë mirë!", "Bravo!", "Super!"],
    ugh: ["Ore!", "Ububu!"],
    thanks: ["Faleminderit", "Rrofsh"],
    bye: ["Mirupafshim", "Ditën e mirë"],
    friend: ["mik"],
    food: ["byrek", "tavë kosi", "fërgesë", "baklava"],
    place: ["the Albanian Alps", "Tirana", "the Riviera", "Prizren", "Berat"],
    lines: {
      idle: ["A guest is sacred in my house. An invader is not a guest."],
    },
  },
  scandinavian: {
    hello: ["Hej", "Hei", "Halló", "God dag"],
    yes: ["Ja", "Jo"],
    no: ["Nej", "Nei"],
    wow: ["Fantastisk!", "Härligt!", "Skål!", "Toppen!"],
    ugh: ["Uff!", "Oj då!", "Huff!", "Hoppsan!"],
    thanks: ["Tack", "Takk", "Tak"],
    bye: ["Hej då", "Ha det", "Farvel"],
    friend: ["min vän", "min venn"],
    food: [
      "meatballs",
      "cinnamon buns",
      "smørrebrød",
      "salmon",
      "lingonberries",
      "brown cheese",
    ],
    place: [
      "the fjords",
      "Stockholm",
      "Copenhagen",
      "Lofoten",
      "Reykjavík",
      "the northern lights",
    ],
    lines: {
      idle: [
        "Fika time. Coffee and a cinnamon bun. Wars can wait.",
        "Not too much, not too little. Lagom. That's how I take land.",
        "There's no bad weather, only bad clothes. Wrap up warm.",
      ],
      attacked: ["{name}, this is very un-hygge of you."],
    },
  },
  finnish: {
    hello: ["Moi", "Hei", "Terve"],
    yes: ["Joo", "Kyllä"],
    no: ["Ei", "Ei käy"],
    wow: ["Mahtavaa!", "Hienoa!", "Sisu!"],
    ugh: ["Voi ei!", "Hitsi!", "Voi vitsi!"],
    thanks: ["Kiitos", "Kiitti"],
    bye: ["Moi moi", "Näkemiin"],
    friend: ["ystävä"],
    food: [
      "karjalanpiirakka",
      "salmon soup",
      "salmiakki",
      "rye bread",
      "pulla",
    ],
    place: [
      "Lapland",
      "Helsinki",
      "the thousand lakes",
      "the sauna by the lake",
    ],
    lines: {
      idle: [
        "I'll be in the sauna. Please hold all invasions.",
        "Sisu: grit, guts and not giving up. Try me.",
      ],
    },
  },
  baltic: {
    hello: ["Tere", "Labas", "Sveiki"],
    yes: ["Jah", "Taip", "Jā"],
    no: ["Ei", "Ne", "Nē"],
    wow: ["Super!", "Puiku!", "Lahe!"],
    ugh: ["Oi!", "Ojoj!", "Vai!"],
    thanks: ["Aitäh", "Ačiū", "Paldies"],
    bye: ["Head aega", "Viso gero", "Uz redzēšanos"],
    friend: ["sõber", "drauge"],
    food: ["black rye bread", "cepelinai", "smoked fish", "kama", "pīrāgi"],
    place: [
      "the Baltic shore",
      "Tallinn",
      "Riga",
      "Vilnius",
      "the old forests",
    ],
    lines: {
      idle: [
        "We sang our way to freedom once. I could sing my way across this map.",
      ],
    },
  },
  // ------------------------------------------------- Middle East, N. Africa
  gulf: {
    hello: ["Marhaba", "Ahlan wa sahlan", "Salam"],
    yes: ["Na'am", "Aiwa", "Tayyib"],
    no: ["La", "Abadan"],
    wow: ["Mumtaz!", "Yalla!", "Jameel!", "Zain!"],
    ugh: ["Ya salam!", "Khalas!", "Ouf!"],
    thanks: ["Shukran", "Shukran jazeelan"],
    bye: ["Ma'a salama", "Yalla, bye"],
    friend: ["ya sadiqi", "habibi"],
    food: ["dates", "kabsa", "Arabic coffee", "luqaimat", "machboos"],
    place: [
      "the desert dunes",
      "the Empty Quarter",
      "the Gulf",
      "Muscat",
      "Riyadh",
      "Dubai",
    ],
    lines: {
      idle: [
        "Come, sit. Arabic coffee and dates for every guest.",
        "Out in the dunes the stars are brighter than any city.",
      ],
      attacked: ["{name}, I poured you coffee and this is how you thank me?"],
    },
  },
  levant: {
    hello: ["Marhaba", "Ahlan", "Kifak"],
    yes: ["Aiwa", "Akeed", "Tayyib"],
    no: ["La", "Abadan"],
    wow: ["Yalla!", "Helo!", "Mumtaz!", "Jameel!"],
    ugh: ["Ya salam!", "Khalas!", "Ya haram!"],
    thanks: ["Shukran", "Merci"],
    bye: ["Ma'a salama", "Bye"],
    friend: ["habibi", "ya sadiqi"],
    food: ["hummus", "falafel", "manakish", "tabbouleh", "knafeh", "shawarma"],
    place: [
      "Beirut",
      "the cedars",
      "Petra",
      "Damascus",
      "the Tigris",
      "Baghdad",
    ],
    lines: {
      idle: [
        "The knafeh is still warm. Who's hungry?",
        "My grandmother says I don't eat enough. She's wrong, but I'll eat more.",
      ],
    },
  },
  egyptian: {
    hello: ["Ahlan", "Salam", "Izzayak"],
    yes: ["Aiwa", "Mashi", "Tab'an"],
    no: ["La'", "Mish momken"],
    wow: ["Gamed!", "Helw awi!", "Tamam!"],
    ugh: ["Ya nahar!", "Ya salam!", "Khalas!"],
    thanks: ["Shukran", "Mersi"],
    bye: ["Ma'a salama", "Salam"],
    friend: ["ya sahbi"],
    food: ["koshari", "ful medames", "ta'ameya", "mahshi", "basbousa"],
    place: ["the Nile", "Cairo", "the pyramids", "Alexandria", "Luxor"],
    lines: {
      idle: [
        "My pyramids have stood for four thousand years. Your borders won't.",
        "Felucca ride on the Nile, anyone? Very relaxing.",
      ],
      attacked: ["{name}, I've outlasted pharaohs. I'll outlast you."],
    },
  },
  maghreb: {
    hello: ["Salam", "Marhaba", "Bonjour"],
    yes: ["Wakha", "Iyeh", "Na'am"],
    no: ["La", "Walou"],
    wow: ["Zwin!", "Mezyan!", "Bezzaf!", "Top!"],
    ugh: ["Ouf!", "Safi!", "Wili!"],
    thanks: ["Shukran", "Saha", "Merci"],
    bye: ["Bslama", "Ma'a salama"],
    friend: ["sahbi", "khoya"],
    food: ["couscous", "tagine", "mint tea", "harira", "msemen", "brik"],
    place: [
      "the Atlas Mountains",
      "the Sahara",
      "Marrakesh",
      "the medina",
      "Tunis",
      "Oran",
    ],
    lines: {
      idle: [
        "Mint tea is poured from high up. It's all in the wrist.",
        "Friday is couscous day. Everyone is invited.",
      ],
    },
  },
  amazigh: {
    hello: ["Azul", "Azul fellawen"],
    thanks: ["Tanemmirt"],
    wow: ["Igerrez!", "Zwin!"],
    bye: ["Ar tufat"],
    food: ["couscous", "tagine", "amlou", "mint tea", "flatbread"],
    place: ["the Atlas", "the Rif", "the Sahara", "Kabylie", "the Draa valley"],
    lines: {
      idle: ["We are the free people. Imazighen. The mountains remember."],
    },
  },
  israeli: {
    hello: ["Shalom", "Ahlan"],
    yes: ["Ken", "Beseder", "Sababa"],
    no: ["Lo", "Ein matzav"],
    wow: ["Sababa!", "Yofi!", "Achla!", "Walla!"],
    ugh: ["Oy!", "Nu, really?", "Ma pitom!"],
    thanks: ["Toda", "Toda raba"],
    bye: ["Lehitraot", "Yalla, bye"],
    friend: ["achi", "chaver"],
    food: ["falafel", "shakshuka", "hummus", "sabich", "rugelach"],
    place: ["Tel Aviv", "the Galilee", "the Negev", "Haifa", "the Dead Sea"],
  },
  persian: {
    hello: ["Salaam", "Dorood"],
    yes: ["Bale", "Hatman", "Chashm"],
    no: ["Na", "Aslan"],
    wow: ["Afarin!", "Aali!", "Kheili khoob!", "Mamnoon!"],
    ugh: ["Vay!", "Ey baba!", "Ay vay!"],
    thanks: ["Merci", "Mamnoon", "Sepas"],
    bye: ["Khodahafez", "Bedrood"],
    friend: ["doost-e man", "azizam"],
    food: [
      "saffron rice",
      "kebab koobideh",
      "tahdig",
      "ghormeh sabzi",
      "pistachios",
      "Persian tea",
    ],
    place: ["Isfahan", "Persepolis", "the Zagros", "Tehran", "Shiraz"],
    lines: {
      idle: [
        "Isfahan is half the world, they say. I'd like the other half too.",
        "The best part of the rice is the crispy tahdig. Fight me.",
        "Nowruz is coming. Spring cleaning first, then conquest.",
      ],
      attacked: ["{name}, I've had empires older than your whole map!"],
    },
  },
  afghan: {
    hello: ["Salaam", "Khush amadid"],
    thanks: ["Tashakor", "Manana"],
    wow: ["Afarin!", "Kheili khub!"],
    bye: ["Khuda hafiz"],
    friend: ["dost"],
    food: ["Kabuli pulao", "mantu", "bolani", "green tea", "kebabs"],
    place: [
      "Kabul",
      "the Hindu Kush",
      "Herat",
      "the Panjshir valley",
      "Bamiyan",
    ],
  },
  // ------------------------------------------------------------ South Asia
  indian: {
    hello: ["Namaste", "Namaskar", "Vanakkam"],
    yes: ["Haan", "Bilkul", "Accha", "Theek hai"],
    no: ["Nahi", "Bilkul nahi"],
    wow: ["Shabash!", "Wah!", "Bahut badhiya!", "Zabardast!"],
    ugh: ["Arre yaar!", "Uff!", "Arre baap re!", "Oho!"],
    thanks: ["Dhanyavaad", "Shukriya"],
    bye: ["Phir milenge", "Alvida", "Chalo, bye"],
    friend: ["yaar", "dost"],
    food: [
      "chai",
      "samosas",
      "biryani",
      "masala dosa",
      "butter chicken",
      "gulab jamun",
      "pani puri",
    ],
    place: [
      "the Ganges",
      "Mumbai",
      "the Himalayas",
      "Kerala",
      "Delhi",
      "Rajasthan",
    ],
    lines: {
      idle: [
        "Chai break! Cutting chai for everyone.",
        "Anyone watching the cricket? No? Then attack later.",
        "My grandmother's biryani could end this war in a day.",
      ],
      attacked: ["Arre yaar, {name}! In the middle of the cricket match?"],
      victory: ["Howzat! Victory! Sweets for everyone!"],
    },
  },
  pakistani: {
    hello: ["Salaam", "Adaab"],
    yes: ["Ji", "Haan", "Bilkul"],
    no: ["Nahin", "Bilkul nahin"],
    wow: ["Shabash!", "Zabardast!", "Kamaal!", "Wah!"],
    ugh: ["Uff!", "Arre yaar!", "Haye!"],
    thanks: ["Shukriya", "Bohat shukriya"],
    bye: ["Khuda hafiz", "Phir milte hain"],
    friend: ["yaar", "bhai"],
    food: ["biryani", "nihari", "chapli kebab", "chai", "haleem", "jalebi"],
    place: ["Lahore", "the Indus", "K2", "Karachi", "the Hunza valley"],
    lines: {
      idle: [
        "Jinne Lahore nahi vekhya, o jamya nahi. If you haven't seen Lahore, you haven't been born.",
      ],
    },
  },
  bangladeshi: {
    hello: ["Nomoshkar", "Salaam", "Kemon achhen"],
    thanks: ["Dhonnobad"],
    wow: ["Darun!", "Khub bhalo!", "Osadharon!"],
    ugh: ["Hay hay!", "Ki kando!"],
    bye: ["Abar dekha hobe", "Bidai"],
    friend: ["bondhu"],
    food: ["hilsa fish", "mishti doi", "fuchka", "biryani", "rasgulla"],
    place: ["Dhaka", "the Sundarbans", "the Padma", "Cox's Bazar"],
  },
  srilankan: {
    hello: ["Ayubowan", "Vanakkam"],
    thanks: ["Istuti", "Nandri"],
    wow: ["Supiri!", "Niyamai!"],
    ugh: ["Aiyo!", "Aney!"],
    bye: ["Gihin ennam", "Poittu varen"],
    friend: ["machan"],
    food: ["Ceylon tea", "hoppers", "kottu roti", "rice and curry", "kiribath"],
    place: ["Kandy", "Colombo", "the hill country", "Sigiriya", "Galle"],
    lines: {
      idle: [
        "Fresh Ceylon tea from the hill country. Best in the world, machan.",
      ],
    },
  },
  himalayan: {
    hello: ["Namaste", "Tashi delek", "Kuzu zangpo"],
    thanks: ["Dhanyabad", "Thuk je che", "Kadrinchey"],
    wow: ["Ramro!", "Babal!"],
    bye: ["Pheri bhetaula"],
    friend: ["sathi"],
    food: ["momos", "dal bhat", "butter tea", "thukpa", "sel roti"],
    place: [
      "the Himalayas",
      "Everest",
      "Kathmandu",
      "Thimphu",
      "the high passes",
    ],
    lines: {
      idle: [
        "Dal bhat power, twenty-four hour! That's how we climb mountains.",
      ],
    },
  },
  // --------------------------------------------------------------- E. Asia
  chinese: {
    hello: ["Nǐ hǎo", "Nǐmen hǎo"],
    yes: ["Hǎo", "Duì", "Méi wèntí"],
    no: ["Bù", "Bù xíng"],
    wow: ["Tài hǎo le!", "Lìhai!", "Hǎo jí le!", "Bàng!"],
    ugh: ["Āiyā!", "Tiān a!", "Zāo le!"],
    thanks: ["Xièxie", "Duōxiè"],
    bye: ["Zàijiàn", "Huítóu jiàn"],
    friend: ["péngyou"],
    food: [
      "dumplings",
      "Peking duck",
      "hot pot",
      "mooncakes",
      "jasmine tea",
      "xiaolongbao",
      "noodles",
    ],
    place: [
      "the Great Wall",
      "the Yangtze",
      "Beijing",
      "the Yellow River",
      "Guilin",
      "Shanghai",
    ],
    lines: {
      idle: [
        "A journey of a thousand miles begins with a single step.",
        "Hot pot tonight. Bring your own chopsticks.",
        "I built a wall once. It was quite long.",
      ],
      attacked: ["Āiyā, {name}! Didn't you see my wall?"],
    },
  },
  taiwanese: {
    hello: ["Nǐ hǎo", "Lí-hó"],
    thanks: ["Xièxie", "To-siā"],
    wow: ["Hǎo bàng!", "Lìhai!"],
    ugh: ["Āiyō!", "Wa!"],
    bye: ["Zàijiàn", "Bàibai"],
    food: [
      "bubble tea",
      "beef noodle soup",
      "pineapple cakes",
      "night market snacks",
    ],
    place: ["Taipei", "Taroko Gorge", "Sun Moon Lake", "Alishan"],
    lines: {
      idle: ["Night market run, anyone? I'm buying the bubble tea."],
    },
  },
  cantonese: {
    hello: ["Néih hóu", "Hello"],
    thanks: ["M̀h'gōi", "Dōjeh"],
    wow: ["Hóu yeh!", "Gwái lēk!"],
    ugh: ["Aiyah!", "Wah!"],
    bye: ["Bāai baai", "Joi gin"],
    food: ["dim sum", "egg tarts", "milk tea", "pineapple buns", "char siu"],
    place: ["Victoria Harbour", "the Peak", "Kowloon", "Lantau"],
    lines: {
      idle: ["Yum cha time. Who's ordering the har gow?"],
    },
  },
  japanese: {
    hello: ["Konnichiwa", "Dōmo", "Ohayō"],
    yes: ["Hai", "Mochiron", "Ii yo"],
    no: ["Iie", "Dame desu", "Muri"],
    wow: ["Sugoi!", "Subarashii!", "Yatta!", "Kakkoii!"],
    ugh: ["Shimatta!", "Uso!", "Mō!", "Masaka!"],
    thanks: ["Arigatō", "Dōmo arigatō"],
    bye: ["Sayōnara", "Mata ne", "Ja ne"],
    friend: ["tomodachi"],
    food: [
      "sushi",
      "ramen",
      "onigiri",
      "mochi",
      "matcha",
      "tempura",
      "takoyaki",
    ],
    place: ["Mount Fuji", "Kyoto", "Tokyo", "Hokkaido", "Osaka", "Nara"],
    lines: {
      idle: [
        "The cherry blossoms are out. Let's have a picnic, then fight.",
        "Fall down seven times, stand up eight. That's my strategy.",
        "My trains are never late. My troops won't be either.",
      ],
      attacked: ["{name}, that was very rude. Shimatta!"],
      victory: ["Yatta! Ramen for everyone!"],
    },
  },
  korean: {
    hello: ["Annyeonghaseyo", "Annyeong"],
    yes: ["Ne", "Mullon"],
    no: ["Aniyo", "Andwae"],
    wow: ["Daebak!", "Jjang!", "Meotjida!"],
    ugh: ["Aigoo!", "Eotteoke!", "Heol!"],
    thanks: ["Gamsahamnida", "Gomawo"],
    bye: ["Annyeonghi gaseyo", "Jal ga"],
    friend: ["chingu"],
    food: [
      "kimchi",
      "bibimbap",
      "Korean barbecue",
      "tteokbokki",
      "bulgogi",
      "kimbap",
    ],
    place: ["Seoul", "Jeju", "the Han River", "Busan", "Seoraksan"],
    lines: {
      idle: [
        "Grilling tonight. Korean barbecue, lots of side dishes.",
        "Aigoo, so much to do. Have you eaten yet?",
      ],
      victory: ["Daebak! Fried chicken party tonight!"],
    },
  },
  steppe: {
    hello: ["Sain baina uu", "Salem", "Salom"],
    yes: ["Tiim", "Iä", "Ha"],
    no: ["Ügüi", "Joq", "Yo'q"],
    wow: ["Zhaksy!", "Gaikhaltai!", "Ajoyib!"],
    ugh: ["Oi bai!", "Voy!", "Aiyy!"],
    thanks: ["Bayarlalaa", "Rakhmet", "Rahmat"],
    bye: ["Bayartai", "Sau bol", "Xayr"],
    friend: ["dos", "dost"],
    food: ["plov", "beshbarmak", "buuz", "samsa", "lagman", "kumis"],
    place: [
      "the steppe",
      "the Altai",
      "Samarkand",
      "the Gobi",
      "Lake Issyk-Kul",
      "the Silk Road",
    ],
    lines: {
      idle: [
        "On the steppe you can see your enemies coming for a week.",
        "The caravans are moving again on the Silk Road. Trade, anyone?",
      ],
    },
  },
  // ------------------------------------------------------------ S.E. Asia
  vietnamese: {
    hello: ["Xin chào", "Chào bạn"],
    yes: ["Vâng", "Được"],
    no: ["Không", "Không được"],
    wow: ["Tuyệt vời!", "Hay quá!", "Đỉnh quá!"],
    ugh: ["Trời ơi!", "Ôi trời!", "Chết rồi!"],
    thanks: ["Cảm ơn", "Cảm ơn nhiều"],
    bye: ["Tạm biệt", "Hẹn gặp lại"],
    friend: ["bạn ơi"],
    food: ["phở", "bánh mì", "spring rolls", "iced coffee", "bún chả"],
    place: ["Hạ Long Bay", "the Mekong", "Hanoi", "Saigon", "Hội An"],
    lines: {
      idle: ["Phở for breakfast, phở for lunch. Victory for dinner."],
    },
  },
  thai: {
    hello: ["Sawasdee", "Sawasdee krub"],
    yes: ["Chai", "Dai"],
    no: ["Mai", "Mai dai"],
    wow: ["Suay!", "Jing jing!", "Saep!", "Geng mak!"],
    ugh: ["Oy!", "Tai laew!", "Aiyo!"],
    thanks: ["Khop khun", "Khop khun mak"],
    bye: ["La gon", "Pai gon na"],
    friend: ["puen"],
    food: [
      "pad thai",
      "tom yum",
      "mango sticky rice",
      "green curry",
      "som tam",
    ],
    place: ["Bangkok", "Chiang Mai", "Phuket", "the Chao Phraya"],
    lines: {
      idle: ["Mai pen rai, everyone. Never mind, no worries."],
    },
  },
  mainland_sea: {
    hello: ["Mingalaba", "Sous-dey", "Sabaidee"],
    thanks: ["Kyay zu tin ba deh", "Orkun", "Khop chai"],
    wow: ["Ko ko!", "La-or nas!"],
    bye: ["Lea haey", "La gon"],
    food: ["mohinga", "fish amok", "laap", "sticky rice", "tea leaf salad"],
    place: [
      "the Mekong",
      "Angkor Wat",
      "Bagan",
      "Luang Prabang",
      "the Irrawaddy",
    ],
  },
  malay: {
    hello: ["Halo", "Apa kabar", "Selamat pagi"],
    yes: ["Ya", "Boleh"],
    no: ["Tidak", "Tak nak"],
    wow: ["Mantap!", "Hebat!", "Bagus!", "Keren!"],
    ugh: ["Aduh!", "Alamak!", "Waduh!"],
    thanks: ["Terima kasih"],
    bye: ["Sampai jumpa", "Jumpa lagi"],
    friend: ["kawan", "teman"],
    food: ["nasi goreng", "satay", "rendang", "nasi lemak", "laksa", "sambal"],
    place: [
      "Bali",
      "Java",
      "Borneo",
      "Kuala Lumpur",
      "Sumatra",
      "the spice islands",
    ],
    lines: {
      idle: ["Sambal on everything. Even on strategy."],
    },
  },
  filipino: {
    hello: ["Kumusta", "Mabuhay", "Magandang araw"],
    yes: ["Oo", "Sige"],
    no: ["Hindi", "Ayoko"],
    wow: ["Galing!", "Astig!", "Ang ganda!", "Sarap!"],
    ugh: ["Hay naku!", "Ay, grabe!", "Aray!"],
    thanks: ["Salamat", "Maraming salamat"],
    bye: ["Paalam", "Ingat"],
    friend: ["kaibigan", "pare"],
    food: ["adobo", "lechon", "halo-halo", "pancit", "lumpia", "sinigang"],
    place: ["Manila", "Palawan", "Boracay", "the rice terraces", "Cebu"],
    lines: {
      idle: ["Karaoke tonight! Who's singing first?"],
    },
  },
  // -------------------------------------------------------------- Oceania
  aussie: {
    hello: ["G'day", "Hiya", "How are you going"],
    yes: ["Too right", "Yeah, nah, yeah", "No worries"],
    no: ["Yeah, nah", "Not a chance"],
    wow: ["Ripper!", "Beauty!", "Bonzer!", "You beauty!"],
    ugh: ["Strewth!", "Crikey!", "Fair dinkum?!", "Oh, rack off!"],
    thanks: ["Cheers", "Ta"],
    bye: ["Hooroo", "See ya", "Catch ya later"],
    friend: ["mate", "cobber"],
    food: [
      "meat pies",
      "Vegemite toast",
      "pavlova",
      "lamingtons",
      "snags off the barbie",
      "flat whites",
    ],
    place: [
      "the Outback",
      "Sydney Harbour",
      "the Great Barrier Reef",
      "the Gold Coast",
      "Tassie",
    ],
    lines: {
      idle: [
        "Barbie's fired up. Bring your own snags.",
        "Everything down here wants to bite you. The troops especially.",
        "She'll be right, mate.",
      ],
      attacked: ["Oi, {name}! Fair go, mate!"],
    },
  },
  kiwi: {
    hello: ["Kia ora", "Gidday"],
    yes: ["Sweet as", "Yeah, nah, yeah"],
    no: ["Yeah, nah", "Nah"],
    wow: ["Sweet as!", "Choice!", "Chur!", "Ka pai!"],
    ugh: ["Oh, gutted!", "Yeah, nah!", "Far out!"],
    thanks: ["Cheers", "Chur", "Kia ora"],
    bye: ["Hei konā rā", "Catch ya"],
    friend: ["bro", "mate"],
    food: [
      "pavlova",
      "hokey pokey ice cream",
      "mince and cheese pies",
      "kūmara chips",
      "fish and chips",
    ],
    place: [
      "Aotearoa",
      "the Southern Alps",
      "Rotorua",
      "Milford Sound",
      "the Remarkables",
    ],
    lines: {
      idle: ["Pavlova is ours, mate. Not up for debate."],
    },
  },
  maori: {
    hello: ["Kia ora", "Tēnā koe", "Mōrena"],
    yes: ["Āe"],
    no: ["Kāo"],
    wow: ["Ka pai!", "Tino pai!", "Ka mau te wehi!"],
    thanks: ["Kia ora", "Ngā mihi"],
    bye: ["Ka kite anō", "Hei konā rā"],
    friend: ["e hoa"],
    food: ["hāngī", "kūmara", "rēwena bread", "kaimoana"],
    place: ["Aotearoa", "the marae", "Rotorua", "the maunga", "the awa"],
    lines: {
      idle: [
        "Whatungarongaro te tangata, toitū te whenua. People pass on, but the land remains.",
      ],
    },
  },
  first_australians: {
    hello: ["Hello", "Welcome"],
    food: ["bush tomatoes", "wattleseed damper", "finger limes", "barramundi"],
    place: ["Country", "the river", "the coast", "the desert", "the ranges"],
    lines: {
      idle: [
        "We have cared for this Country for more than sixty thousand years.",
        "Every river and hill here has a story. Mind where you march.",
      ],
      attacked: ["{name}, you are walking on Country. Show some respect."],
    },
  },
  islands: {
    hello: ["Bula", "Talofa", "Mālō e lelei", "Aloha"],
    yes: ["Io", "Ioe"],
    wow: ["Mālie!", "Sweet!", "Maika'i!"],
    ugh: ["Auē!", "Aue!"],
    thanks: ["Vinaka", "Fa'afetai", "Mahalo", "Mālō"],
    bye: ["Moce", "Tōfā", "A hui hou"],
    friend: ["uso", "my friend"],
    food: [
      "taro",
      "fresh coconut",
      "poke",
      "kokoda",
      "breadfruit",
      "shave ice",
    ],
    place: [
      "the lagoon",
      "the reef",
      "the islands",
      "the volcano",
      "the beach",
    ],
    lines: {
      idle: [
        "Island time, everyone. We'll get there when we get there.",
        "The surf is up. War can wait.",
      ],
    },
  },
  indian_ocean: {
    hello: ["Bonzour", "Hello", "Salama"],
    thanks: ["Mersi", "Misaotra"],
    wow: ["Top!", "Super!"],
    bye: ["Orevwar", "Veloma"],
    food: [
      "octopus curry",
      "fresh coconut",
      "grilled fish",
      "rougaille",
      "vanilla",
    ],
    place: ["the lagoon", "the reef", "the Indian Ocean", "the white beaches"],
  },
  malagasy: {
    hello: ["Salama", "Manao ahoana"],
    thanks: ["Misaotra", "Misaotra betsaka"],
    wow: ["Tsara be!", "Mahafinaritra!"],
    bye: ["Veloma"],
    food: ["romazava", "vanilla", "lychees", "mofo gasy", "zebu stew"],
    place: [
      "the Avenue of the Baobabs",
      "Antananarivo",
      "the rainforest",
      "Nosy Be",
    ],
    lines: {
      idle: ["The lemurs are watching. They judge everyone equally."],
    },
  },
  // --------------------------------------------------------------- Africa
  nigerian: {
    hello: ["How far?", "Bawo ni", "Sannu", "Kedu"],
    yes: ["Na so", "Oya", "Correct"],
    no: ["Abeg, no", "Lai lai", "No be so"],
    wow: ["Oshey!", "E choke!", "Correct!", "Na wa!"],
    ugh: ["Chai!", "Haba!", "Wahala!", "Ehn ehn!"],
    thanks: ["Thank you o", "Ese", "Nagode", "Daalụ"],
    bye: ["Odabo", "Later o", "Sai anjima"],
    friend: ["my guy", "my padi"],
    food: [
      "jollof rice",
      "suya",
      "puff-puff",
      "pounded yam and egusi",
      "chin chin",
      "pepper soup",
    ],
    place: ["Lagos", "Abuja", "the Niger", "Kano", "Calabar", "Enugu"],
    lines: {
      idle: [
        "Nigerian jollof is the best jollof. This is not up for discussion.",
        "Lagos traffic is worse than this war. I'm not even worried.",
        "No wahala, everyone. Chill.",
      ],
      attacked: ["Haba, {name}! You want wahala? Wahala is coming!"],
      victory: ["Oshey! Owambe party tonight, everybody come!"],
    },
  },
  ghanaian: {
    hello: ["Akwaaba", "Ɛte sɛn", "Chale"],
    yes: ["Aane", "Yoo"],
    no: ["Daabi"],
    wow: ["Ayekoo!", "Chale, nice!", "Ɛyɛ!"],
    ugh: ["Ei!", "Chale, why?", "Herh!"],
    thanks: ["Medaase", "Ayekoo"],
    bye: ["Nante yie", "See you, chale"],
    friend: ["chale", "my brother"],
    food: [
      "jollof",
      "kelewele",
      "banku and tilapia",
      "fufu",
      "waakye",
      "red red",
    ],
    place: ["Accra", "the Volta", "Kumasi", "Cape Coast", "Lake Volta"],
    lines: {
      idle: [
        "Ghana jollof is the real jollof. I have spoken.",
        "Akwaaba, everyone! Welcome is in our name.",
      ],
    },
  },
  west_african: {
    hello: ["Kushe", "Hello o"],
    thanks: ["Tenki", "Thank you"],
    wow: ["Fine fine!", "Na so!"],
    bye: ["Wi go si back", "Later"],
    food: ["jollof rice", "cassava leaf stew", "groundnut soup", "plantain"],
    place: ["Freetown", "Monrovia", "the Gambia River", "the Atlantic coast"],
  },
  francophone_africa: {
    hello: ["Bonjour", "Salut", "Nanga def"],
    yes: ["Oui", "Waaw"],
    no: ["Non", "Déedéet"],
    wow: ["C'est génial!", "Formidable!", "Ça va aller!"],
    ugh: ["Ehh!", "Aïe!", "C'est pas possible!"],
    thanks: ["Merci", "Jërëjëf", "I ni ce"],
    bye: ["Au revoir", "Ba beneen yoon"],
    friend: ["mon frère", "mon ami"],
    food: ["thiéboudienne", "attiéké", "yassa chicken", "alloco", "mafé"],
    place: [
      "Dakar",
      "Abidjan",
      "the Niger River",
      "Timbuktu",
      "the Sahel",
      "Lomé",
    ],
    lines: {
      idle: [
        "Teranga, everyone. Hospitality. Come in, sit, eat.",
        "The griots will sing about this war. Let's make it a good song.",
      ],
    },
  },
  central_african: {
    hello: ["Mbote", "Bonjour", "Jambo"],
    thanks: ["Matondo", "Merci"],
    wow: ["Malamu!", "Formidable!", "Mobimba!"],
    ugh: ["Mama!", "Aïe!"],
    bye: ["Tokomonana", "Au revoir"],
    friend: ["ndeko", "mon ami"],
    food: ["moambe chicken", "fufu", "pondu", "fried plantains", "ndolé"],
    place: [
      "the Congo River",
      "Kinshasa",
      "the rainforest",
      "Lake Tanganyika",
      "Brazzaville",
    ],
    lines: {
      idle: ["Put on some rumba. The war can dance a little first."],
    },
  },
  east_african: {
    hello: ["Jambo", "Habari", "Mambo"],
    yes: ["Ndiyo", "Sawa"],
    no: ["Hapana"],
    wow: ["Poa!", "Safi!", "Hongera!", "Sawa sawa!"],
    ugh: ["Aiya!", "Wueh!", "Hata!"],
    thanks: ["Asante", "Asante sana"],
    bye: ["Kwaheri", "Tutaonana"],
    friend: ["rafiki", "ndugu"],
    food: ["ugali", "nyama choma", "chapati", "pilau", "mandazi", "chai"],
    place: [
      "Kilimanjaro",
      "the Serengeti",
      "Lake Victoria",
      "Zanzibar",
      "Nairobi",
      "the Rift Valley",
    ],
    lines: {
      idle: [
        "Pole pole, everyone. Slowly, slowly. Haraka haraka haina baraka.",
        "Hakuna matata. No worries. Not yet, anyway.",
        "Nyama choma tonight. Bring friends.",
      ],
      attacked: ["{name}! Pole pole! Slow down!"],
    },
  },
  horn: {
    hello: ["Selam", "Salaan", "Tena yistilign"],
    yes: ["Awo", "Haa"],
    no: ["Aydelem", "Maya"],
    wow: ["Konjo!", "Betam tiru!", "Aad u fiican!"],
    ugh: ["Wey!", "Ere!", "Waar!"],
    thanks: ["Ameseginalehu", "Mahadsanid"],
    bye: ["Ciao", "Nabad gelyo", "Dehna hun"],
    friend: ["wedaje", "saaxiib"],
    food: ["injera", "doro wat", "coffee", "canjeero", "shiro", "sambusa"],
    place: [
      "Addis Ababa",
      "the Simien Mountains",
      "Lalibela",
      "Mogadishu",
      "the Blue Nile",
    ],
    lines: {
      idle: [
        "Coffee ceremony time. Three cups. Nobody leaves before the third.",
        "We gave the world coffee. You're welcome.",
      ],
    },
  },
  sudanese: {
    hello: ["Salam", "Marhaba"],
    thanks: ["Shukran"],
    wow: ["Tamam!", "Jamil!"],
    bye: ["Ma'a salama"],
    food: ["ful", "kisra", "aseeda", "hibiscus tea", "spiced coffee"],
    place: ["the Nile", "Khartoum", "the meeting of the Niles", "Meroë"],
  },
  south_sudanese: {
    hello: ["Hello", "Salam"],
    thanks: ["Thank you", "Shukran"],
    wow: ["Very good!", "Tamam!"],
    food: ["kisra", "asida", "peanut stew", "tilapia"],
    place: ["Juba", "the White Nile", "the Sudd", "the savanna"],
  },
  southern_african: {
    hello: ["Sawubona", "Howzit", "Dumela", "Molo"],
    yes: ["Ja", "Yebo"],
    no: ["Aikona", "Nee"],
    wow: ["Lekker!", "Sharp sharp!", "Eish, nice!", "Shap!"],
    ugh: ["Eish!", "Ag, no man!", "Hayibo!"],
    thanks: ["Ngiyabonga", "Dankie", "Enkosi"],
    bye: ["Sala kahle", "Totsiens", "Cheers"],
    friend: ["my bru", "mfethu"],
    food: ["braai", "bunny chow", "biltong", "bobotie", "boerewors", "pap"],
    place: [
      "Table Mountain",
      "the Drakensberg",
      "the Kalahari",
      "Victoria Falls",
      "the Okavango",
      "Joburg",
    ],
    lines: {
      idle: [
        "Braai's on. Bring your own meat, and maybe some patience.",
        "Ubuntu, everyone. I am because we are.",
        "Is it a braai or a barbecue? It's a braai. Don't argue.",
      ],
      attacked: ["Eish, {name}! Not cool, my bru!"],
    },
  },
  lusophone_africa: {
    hello: ["Olá", "Bom dia", "Saudações"],
    yes: ["Sim", "Claro"],
    no: ["Não"],
    wow: ["Bué fixe!", "Que bom!", "Maravilha!"],
    ugh: ["Aiué!", "Caramba!"],
    thanks: ["Obrigado"],
    bye: ["Tchau", "Até logo"],
    friend: ["meu kamba", "meu amigo"],
    food: ["piri-piri chicken", "muamba", "matapa", "cachupa", "funge"],
    place: [
      "Luanda",
      "Maputo",
      "the Zambezi",
      "Cabo Verde",
      "the Indian Ocean coast",
    ],
    lines: {
      idle: ["Someone put on some kizomba. Battles go better with music."],
    },
  },
  // ------------------------------------------------------------ Americas
  american: {
    hello: ["Hey there", "Howdy", "What's up"],
    yes: ["You bet", "Sure thing", "Heck yeah"],
    no: ["Nope", "No way", "Not happening"],
    wow: ["Awesome!", "Sweet!", "Heck yeah!", "Nice!"],
    ugh: ["Oh, come on!", "Darn it!", "Seriously?!", "Shoot!"],
    thanks: ["Thanks a bunch", "Much appreciated", "Thanks"],
    bye: ["See ya", "Take care", "Later"],
    friend: ["buddy", "pal"],
    food: [
      "apple pie",
      "burgers",
      "barbecue",
      "hot dogs",
      "mac and cheese",
      "pancakes",
    ],
    place: [
      "the Grand Canyon",
      "Route 66",
      "the Rockies",
      "New York",
      "the Mississippi",
    ],
    lines: {
      idle: [
        "Who wants to go halves on a pizza? Extra large.",
        "Fourth of July fireworks are early this year. Everyone duck.",
        "Road trip! Anyone need a ride along Route 66?",
      ],
      attacked: ["Hey, {name}! Not cool, buddy. Not cool."],
    },
  },
  us_northeast: {
    hello: ["Hey", "Hi there", "Morning"],
    yes: ["Yeah, sure", "Totally"],
    no: ["No way", "Not a chance"],
    wow: ["Wicked good!", "That's awesome!", "Nice one!"],
    ugh: ["Oh, come on!", "Seriously?", "Get outta here!"],
    thanks: ["Thanks", "Appreciate it"],
    bye: ["See ya", "Later"],
    friend: ["buddy", "pal"],
    food: [
      "bagels",
      "New York pizza",
      "clam chowder",
      "Philly cheesesteaks",
      "lobster rolls",
      "maple syrup",
    ],
    place: [
      "Boston Harbor",
      "the Hudson",
      "the Berkshires",
      "Cape Cod",
      "Manhattan",
      "the Green Mountains",
    ],
    lines: {
      idle: [
        "Leaf-peeping season is the best season. Don't @ me.",
        "It's not traffic, it's character building.",
        "Whoever's hogging the ferry, move it.",
      ],
    },
  },
  us_south: {
    hello: ["Hey y'all", "Howdy", "Well, hey there"],
    yes: ["Yes ma'am", "Sure enough", "You bet"],
    no: ["Bless your heart, no", "No sir"],
    wow: ["Well, I'll be!", "Hot dog!", "Mighty fine!", "Lord, that's good!"],
    ugh: ["Well, shoot!", "Good gracious!", "Oh, for heaven's sake!"],
    thanks: ["Thank you kindly", "Much obliged"],
    bye: ["Y'all come back now", "Take care, now"],
    friend: ["honey", "partner"],
    food: [
      "sweet tea",
      "biscuits and gravy",
      "fried chicken",
      "grits",
      "pecan pie",
      "barbecue",
    ],
    place: [
      "the Smokies",
      "Nashville",
      "the Blue Ridge",
      "the Gulf Coast",
      "Savannah",
      "the Ozarks",
    ],
    lines: {
      idle: [
        "Pull up a rocking chair. Sweet tea's on the porch.",
        "It's so humid you could swim to the front lines.",
        "Mama always said, never show up anywhere empty-handed. I brought pie.",
      ],
      attacked: ["Well, bless your heart, {name}. You're gonna regret that."],
    },
  },
  cajun: {
    hello: ["Hey there, cher", "Comment ça va"],
    yes: ["Yeah, you right", "Oui"],
    wow: ["Laissez les bons temps rouler!", "Ça c'est bon!", "Whoo!"],
    ugh: ["Mais, non!", "Oh, mais yeah!"],
    thanks: ["Merci, cher", "Thank you"],
    bye: ["À la prochaine", "See ya later, alligator"],
    friend: ["cher", "my friend"],
    food: [
      "gumbo",
      "jambalaya",
      "beignets",
      "crawfish étouffée",
      "po'boys",
      "boudin",
    ],
    place: [
      "the bayou",
      "the French Quarter",
      "the Mississippi",
      "Acadiana",
      "the swamp",
    ],
    lines: {
      idle: [
        "Crawfish boil this weekend. Bring a big appetite.",
        "Laissez les bons temps rouler! Let the good times roll!",
      ],
    },
  },
  us_midwest: {
    hello: ["Hey there", "Oh, hi", "Hiya"],
    yes: ["You betcha", "Oh, for sure", "Yah"],
    no: ["Oh, I don't think so", "Nah"],
    wow: ["Oh, neat!", "Super!", "Holy cow!", "Okie dokie!"],
    ugh: ["Ope!", "Oh, for cryin' out loud!", "Oh, geez!", "Uff da!"],
    thanks: ["Thanks a bunch", "Thanks so much"],
    bye: ["See you later", "Take it easy"],
    friend: ["neighbour", "pal"],
    food: [
      "hotdish",
      "cheese curds",
      "deep-dish pizza",
      "corn on the cob",
      "bratwurst",
      "pie",
    ],
    place: [
      "the Great Lakes",
      "the cornfields",
      "Chicago",
      "the prairie",
      "the Mississippi",
      "the lake cabin",
    ],
    lines: {
      idle: [
        "Ope, just gonna squeeze right past your border there.",
        "Brought a casserole for the war effort. It's got tater tots on it.",
        "Weather's nice. Gonna be a cold one later, though.",
      ],
      attacked: ["Ope! {name}, that's not very neighbourly."],
    },
  },
  us_southwest: {
    hello: ["Howdy", "Hey, partner"],
    yes: ["Yes sir", "You bet"],
    no: ["Nope", "Not on your life"],
    wow: ["Yeehaw!", "Dang, that's good!", "Well, alright!"],
    ugh: ["Well, dang!", "Dadgummit!", "Aw, shucks!"],
    thanks: ["Thank you kindly", "Much obliged"],
    bye: ["Happy trails", "So long, partner"],
    friend: ["partner", "amigo"],
    food: [
      "brisket",
      "Tex-Mex",
      "green chile",
      "chili",
      "breakfast tacos",
      "kolaches",
    ],
    place: [
      "the desert",
      "the Alamo",
      "the Grand Canyon",
      "Big Bend",
      "the Rio Grande",
      "the Las Vegas Strip",
    ],
    lines: {
      idle: [
        "Everything's bigger out here. Especially my borders.",
        "It's a dry heat. That's what we tell ourselves.",
        'Red or green chile? Say "Christmas" and get both.',
      ],
      attacked: ["Well, dang, {name}. Those are fighting words."],
    },
  },
  us_west: {
    hello: ["Hey, dude", "Hey there", "Hiya"],
    yes: ["Totally", "For sure", "Hella yes"],
    no: ["Nah, man", "No way, dude"],
    wow: ["Rad!", "Gnarly!", "Stoked!", "Epic!"],
    ugh: ["Bummer!", "Not cool, dude!", "Harsh!", "Dude, seriously?"],
    thanks: ["Thanks, dude", "Appreciate it"],
    bye: ["Later, dude", "Peace out"],
    friend: ["dude", "bro"],
    food: [
      "fish tacos",
      "avocado toast",
      "sourdough",
      "burritos",
      "craft coffee",
      "huckleberry pie",
    ],
    place: [
      "the Pacific",
      "Yellowstone",
      "the Golden Gate",
      "Yosemite",
      "the Cascades",
      "the Rockies",
    ],
    lines: {
      idle: [
        "Surf's up. Back in an hour.",
        "Hiked a fourteener this morning. What did you do?",
        "It's raining again up north. Great coffee weather, though.",
      ],
      attacked: ["Dude, {name}! Totally not chill!"],
    },
  },
  us_dc: {
    hello: ["Good morning", "Hello", "Hi, all"],
    yes: ["Yes, on background", "Agreed, in principle"],
    no: ["That's a non-starter", "Not without a markup"],
    wow: ["That's a win!", "Bipartisan victory!", "Great optics!"],
    ugh: [
      "That's a bad look!",
      "Per my last email!",
      "That's above my pay grade!",
    ],
    thanks: ["Thanks", "Much appreciated"],
    bye: ["Let's circle back", "Let's take this offline"],
    friend: ["my friend across the aisle"],
    food: [
      "half-smokes",
      "jumbo slices",
      "Ethiopian food",
      "crab cakes",
      "cherry blossom lattes",
    ],
    place: [
      "the Mall",
      "Capitol Hill",
      "the Potomac",
      "the Beltway",
      "Georgetown",
      "the Metro",
    ],
    lines: {
      idle: [
        "Let's form a working group to discuss the formation of a working group.",
        "I'll need that border dispute in a two-page memo by close of business.",
        "The Red Line is delayed again. Single-tracking. As always.",
        "Can we put a pin in this war and circle back after recess?",
        "My lobbyist says this map is a great opportunity.",
      ],
      attacked: [
        "{name}, this is unconstitutional! I'm calling a hearing!",
        "{name}, I'm going to need you to submit that attack in writing.",
      ],
      allianceAccepted: ["Love this. Let's do a joint press release, {name}."],
      betrayed: ["{name}, I'm leaking this to the press."],
    },
  },
  canadian: {
    hello: ["Hey there", "Hi", "Bonjour, hi"],
    yes: ["You bet", "For sure", "Yeah, eh"],
    no: ["Sorry, but no", "Not today, bud"],
    wow: ["Beauty!", "Right on!", "Awesome, eh?", "Nice one!"],
    ugh: [
      "Oh, sorry, but come on!",
      "Give your head a shake!",
      "Oh, for Pete's sake!",
    ],
    thanks: ["Thanks, eh", "Thanks a bunch", "Merci"],
    bye: ["See you later", "Bye for now", "Take care, eh"],
    friend: ["buddy", "bud"],
    food: [
      "poutine",
      "maple syrup",
      "butter tarts",
      "Nanaimo bars",
      "peameal bacon",
    ],
    place: [
      "the Rockies",
      "Toronto",
      "the Prairies",
      "Lake Louise",
      "Niagara Falls",
      "the Maritimes",
    ],
    lines: {
      idle: [
        "Sorry, is this your border? Sorry. I'll just take it anyway. Sorry.",
        "Hockey night tonight. Please schedule all invasions around it.",
        "It's only minus thirty. Practically T-shirt weather.",
      ],
      attacked: ["Sorry, {name}, but that's really not okay."],
      victory: ["Beauty! Double-doubles all round, eh!"],
    },
  },
  quebecois: {
    hello: ["Allô", "Bonjour"],
    yes: ["Oui", "Ben oui", "Certain"],
    no: ["Non", "Pantoute"],
    wow: ["Malade!", "Écoeurant!", "C'est bon en titi!"],
    ugh: ["Voyons donc!", "Ben là!", "Câline!"],
    thanks: ["Merci", "Merci ben"],
    bye: ["Bye-bye", "À la prochaine"],
    friend: ["mon chum"],
    food: [
      "poutine",
      "tourtière",
      "maple taffy",
      "smoked meat",
      "pouding chômeur",
    ],
    place: ["Montréal", "the St Lawrence", "Québec City", "the Laurentians"],
    lines: {
      idle: ["Sugar shack season! Maple taffy on the snow for everybody."],
    },
  },
  mexican: {
    hello: ["Hola", "Qué onda", "Buenas"],
    yes: ["Sí", "Órale", "Claro que sí"],
    no: ["No", "Para nada", "Ni modo"],
    wow: ["¡Qué padre!", "¡Órale!", "¡Chido!", "¡Ándale!"],
    ugh: ["¡Híjole!", "¡Ay, caramba!", "¡No manches!", "¡Ay, no!"],
    thanks: ["Gracias", "Mil gracias"],
    bye: ["Adiós", "Nos vemos", "Hasta luego"],
    friend: ["amigo", "compadre"],
    food: [
      "tacos al pastor",
      "tamales",
      "mole",
      "elote",
      "pozole",
      "guacamole",
    ],
    place: [
      "Mexico City",
      "Oaxaca",
      "the Yucatán",
      "Guadalajara",
      "Chichén Itzá",
      "the Sierra Madre",
    ],
    lines: {
      idle: [
        "Street tacos at midnight. The best kind of tacos.",
        "Grandma's mole has thirty ingredients. My battle plan has three.",
        "¡Órale! Who brought the mariachis?",
      ],
      attacked: ["¡Híjole, {name}! Not before I finish my tacos!"],
      victory: ["¡Ándale! Fiesta and fireworks tonight!"],
    },
  },
  central_american: {
    hello: ["Hola", "Buenas", "Pura vida"],
    yes: ["Sí", "Va pues", "Simón"],
    no: ["No", "Ni loco"],
    wow: ["¡Pura vida!", "¡Qué chivo!", "¡Tuanis!", "¡Qué bueno!"],
    ugh: ["¡Ay, no!", "¡Púchica!", "¡Chuta!"],
    thanks: ["Gracias", "Muchas gracias"],
    bye: ["Adiós", "Nos vemos"],
    friend: ["mae", "amigo"],
    food: ["pupusas", "gallo pinto", "baleadas", "tamales", "plantains"],
    place: [
      "the volcanoes",
      "Lake Atitlán",
      "the cloud forest",
      "the Panama Canal",
      "Tikal",
    ],
    lines: {
      idle: ["Pura vida, everyone. Pure life. Relax a little."],
    },
  },
  caribbean_spanish: {
    hello: ["Hola", "Qué tal", "Wepa"],
    yes: ["Sí", "Dale"],
    no: ["No", "Ni pensarlo"],
    wow: ["¡Qué chévere!", "¡Wepa!", "¡Bacano!", "¡Qué rico!"],
    ugh: ["¡Ay, bendito!", "¡Ay, no!", "¡Ay, mi madre!"],
    thanks: ["Gracias", "Mil gracias"],
    bye: ["Chao", "Nos vemos"],
    friend: ["mi pana", "hermano"],
    food: [
      "arepas",
      "mofongo",
      "tostones",
      "café cubano",
      "empanadas",
      "arroz con pollo",
    ],
    place: [
      "Havana",
      "San Juan",
      "Cartagena",
      "the Caribbean coast",
      "Caracas",
      "Santo Domingo",
    ],
    lines: {
      idle: ["Somebody turn up the salsa. Battles go better with rhythm."],
    },
  },
  andean: {
    hello: ["Hola", "Buenas", "Allillanchu"],
    yes: ["Sí", "Ya", "Claro"],
    no: ["No", "Ni hablar"],
    wow: ["¡Bacán!", "¡Qué chévere!", "¡Buenazo!"],
    ugh: ["¡Ay, no!", "¡Chuta!", "¡Achachay!"],
    thanks: ["Gracias", "Sulpayki"],
    bye: ["Chao", "Nos vemos"],
    friend: ["pata", "hermano"],
    food: [
      "ceviche",
      "empanadas",
      "lomo saltado",
      "quinoa",
      "salteñas",
      "pisco",
    ],
    place: [
      "the Andes",
      "Machu Picchu",
      "Lake Titicaca",
      "the Atacama",
      "Patagonia",
      "Cusco",
    ],
    lines: {
      idle: [
        "The air up here is thin. My patience too.",
        "Coca tea for the altitude, anyone?",
      ],
    },
  },
  rioplatense: {
    hello: ["Hola", "Che", "Buenas"],
    yes: ["Sí", "Dale", "Obvio"],
    no: ["No", "Ni loco", "Para nada"],
    wow: ["¡Bárbaro!", "¡Genial!", "¡Buenísimo!", "¡Qué copado!"],
    ugh: ["¡Qué macana!", "¡No, che!", "¡Uy!"],
    thanks: ["Gracias", "Gracias, che"],
    bye: ["Chau", "Nos vemos"],
    friend: ["che", "amigo"],
    food: [
      "asado",
      "empanadas",
      "mate",
      "dulce de leche",
      "alfajores",
      "chimichurri",
    ],
    place: [
      "Buenos Aires",
      "the Pampas",
      "Patagonia",
      "Montevideo",
      "the Río de la Plata",
    ],
    lines: {
      idle: [
        "The mate is going round. Don't say thank you unless you're done.",
        "Asado on Sunday. The grill master is not to be questioned.",
      ],
      attacked: ["¡Che, {name}! Not during the asado!"],
    },
  },
  brazilian: {
    hello: ["Oi", "E aí", "Olá"],
    yes: ["Sim", "Beleza", "Com certeza"],
    no: ["Não", "De jeito nenhum"],
    wow: ["Que legal!", "Show de bola!", "Nossa!", "Maravilha!"],
    ugh: ["Nossa senhora!", "Caramba!", "Que isso!"],
    thanks: ["Obrigado", "Valeu"],
    bye: ["Tchau", "Até mais", "Falou"],
    friend: ["meu amigo", "parceiro"],
    food: [
      "feijoada",
      "pão de queijo",
      "brigadeiros",
      "açaí",
      "churrasco",
      "coxinhas",
    ],
    place: [
      "Rio",
      "the Amazon",
      "São Paulo",
      "Copacabana",
      "Bahia",
      "Iguaçu Falls",
    ],
    lines: {
      idle: [
        "Who's coming to the churrasco? There's always room.",
        "Futebol later? I'll be in goal. And on your border.",
        "Carnival is coming. Practise your samba.",
      ],
      attacked: ["Que isso, {name}?! I was at the beach!"],
      victory: ["Gooooool! I mean, victory! Carnival!"],
    },
  },
  caribbean: {
    hello: ["Wah gwaan", "Hello", "Good day"],
    yes: ["Yes", "For real"],
    no: ["No", "Nah"],
    wow: ["Irie!", "Big up!", "Wicked!", "Bless up!"],
    ugh: ["Cho!", "Oh no!", "Oh gosh!"],
    thanks: ["Thanks", "Respect"],
    bye: ["Walk good", "Later", "Bless"],
    friend: ["bredren", "fam"],
    food: [
      "jerk chicken",
      "ackee and saltfish",
      "roti",
      "conch fritters",
      "doubles",
      "rum cake",
    ],
    place: [
      "Montego Bay",
      "the Blue Mountains",
      "Port of Spain",
      "Nassau",
      "the Caribbean Sea",
    ],
    lines: {
      idle: [
        "Jerk chicken on the grill and the beach is calling. Life is good.",
        "Out of many, one people. That's how we do it.",
        "Steel pan is warming up. Big carnival after this war.",
      ],
    },
  },
  haitian: {
    hello: ["Bonjou", "Sak pase"],
    yes: ["Wi"],
    no: ["Non"],
    wow: ["Bèl bagay!", "Anfòm!"],
    ugh: ["Woy!", "Anmwe!"],
    thanks: ["Mèsi", "Mèsi anpil"],
    bye: ["Orevwa", "Na wè pita"],
    friend: ["zanmi"],
    food: [
      "griot",
      "diri ak djon djon",
      "pikliz",
      "soup joumou",
      "fried plantains",
    ],
    place: ["Port-au-Prince", "the Citadelle", "Jacmel", "Cap-Haïtien"],
    lines: {
      idle: [
        "We were the first nation born of a revolt against slavery. Remember that.",
      ],
    },
  },
  // --------------------------------------------------------- Custom maps
  florida: {
    hello: ["Hey y'all", "Hey there, sunshine", "Hi there"],
    yes: ["Heck yeah", "You bet"],
    no: ["Nope", "Not in this heat"],
    wow: ["Hot dang!", "That's beachy!", "Sunshine State, baby!", "Sweet!"],
    ugh: ["Oh, for Pete's sake!", "Lord, it's hot!", "Oh, come on!"],
    thanks: ["Thanks, y'all", "Thank you kindly"],
    bye: ["See ya at the beach", "Later, gator"],
    friend: ["buddy", "neighbour"],
    food: [
      "key lime pie",
      "Cuban sandwiches",
      "stone crab",
      "fresh orange juice",
      "boiled peanuts",
      "grouper sandwiches",
    ],
    place: [
      "the Everglades",
      "the Space Coast",
      "the Gulf",
      "the Keys",
      "the springs",
      "I-4",
    ],
    lines: {
      idle: [
        "It's raining with the sun out again. Typical.",
        "Watch out for the love bugs, everyone.",
        "Hurricane season? We just call that Tuesday.",
        "If you see a gator, leave it be. It was here first.",
        "Rocket launch at the Cape tonight. Everybody look east.",
        "It's ninety-five degrees and the AC just died. Pray for me.",
      ],
      attacked: [
        "{name}, it's too hot for this!",
        "Hey, {name}, this is a no-wake zone! Back off!",
      ],
      victory: ["Hot dang! Key lime pie for the whole state!"],
    },
  },
  orlando: {
    hello: ["Hey y'all", "Hey, neighbour", "Hi there"],
    wow: ["Hot dang!", "Magical!", "Sweet!"],
    ugh: ["Oh, come on!", "Not again!", "Ugh, I-4 traffic!"],
    bye: ["See ya on I-4", "Later, gator"],
    food: [
      "Cuban sandwiches",
      "key lime pie",
      "orange juice",
      "boiled peanuts",
      "food truck tacos",
    ],
    place: [
      "Lake Eola",
      "I-4",
      "International Drive",
      "the 408",
      "Lake Nona",
      "UCF",
    ],
    lines: {
      idle: [
        "Construction on I-4 will finish one day. Not today.",
        "Tourists everywhere. Locals know the back roads.",
        "Paddle boats on Lake Eola later? Watch out for the swans.",
        "Pay the toll on the 408 and get there faster. Or don't. It's a free country.",
        "Afternoon thunderstorm at three, like clockwork.",
      ],
      attacked: [
        "{name}, I already have to deal with I-4. Now this?",
        "Hey, {name}, this isn't a theme park ride!",
      ],
    },
  },
  apopka: {
    hello: ["Hey y'all", "Hey, neighbour", "Howdy"],
    yes: ["You bet", "Sure thing"],
    no: ["Nope", "Not a chance"],
    wow: ["Go Blue Darters!", "Hot dang!", "Now that's growing!", "Sweet!"],
    ugh: ["Oh, come on!", "Well, shoot!", "Good grief!"],
    thanks: ["Thanks, neighbour", "Much obliged"],
    bye: ["See ya on 441", "Later, y'all"],
    friend: ["neighbour", "buddy"],
    food: [
      "sweet tea",
      "boiled peanuts",
      "Southern barbecue",
      "fresh oranges",
      "fried catfish",
    ],
    place: [
      "Lake Apopka",
      "Wekiwa Springs",
      "the fern nurseries",
      "Kit Land Nelson Park",
      "Highway 441",
      "Rock Springs Run",
    ],
    lines: {
      idle: [
        "Apopka, the Indoor Foliage Capital of the World, sends its regards.",
        "Wekiwa Springs is seventy-two degrees all year. Come cool off.",
        "My ferns are thriving. Can't say the same for your attack.",
        "Every road out here ends up on 441 eventually.",
        "Kayak down Rock Springs Run. It'll calm you right down.",
        "See you at the Art and Foliage Festival!",
        "Lake Apopka's birds are out this morning. Prettiest drive in Central Florida.",
      ],
      attacked: [
        "{name}, get off my lawn! I just planted those!",
        "{name}, I've survived Florida summers. I'll survive you.",
      ],
      victory: ["Go Blue Darters! Apopka takes it all!"],
      allianceAccepted: ["All right, {name}! Apopka strong!"],
    },
  },
  colonial: {
    hello: ["Good day to you", "Well met", "Your servant"],
    yes: ["Aye", "Indeed", "Most certainly"],
    no: ["Nay", "By no means", "I think not"],
    wow: ["Huzzah!", "Capital!", "Splendid!", "Most excellent!"],
    ugh: ["Zounds!", "Egad!", "Fie upon it!", "Odds bodkins!"],
    thanks: ["I thank you kindly", "Much obliged", "My thanks"],
    bye: ["Fare thee well", "Adieu", "Good day, sir"],
    friend: ["good sir", "my good fellow", "neighbour"],
    food: [
      "johnnycakes",
      "apple cider",
      "corn pudding",
      "salted cod",
      "succotash",
      "untaxed tea",
    ],
    place: [
      "the harbour",
      "Philadelphia",
      "the Chesapeake",
      "the Hudson",
      "Charles Town",
      "the Blue Ridge",
    ],
    lines: {
      idle: [
        "No taxation without representation!",
        "I shall write a strongly worded pamphlet about this.",
        "A penny saved is a penny earned, as Mr Franklin says.",
        "The Assembly sits tomorrow. Bring your wig.",
        "Has anyone seen the post rider? My letters are a fortnight late.",
        "Common sense, gentlemen. Common sense.",
      ],
      attacked: [
        "Zounds! {name}, the Assembly shall hear of this outrage!",
        "Pray, {name}, do not tread on me.",
        "{name}, you are no better than a redcoat!",
      ],
      allianceAccepted: [
        "Huzzah! Join, or die, {name}. Well, join. Join is good.",
      ],
      betrayed: ["Treachery! {name}, you are a Tory in disguise!"],
      victory: ["Huzzah! Ring the bells in every steeple!"],
    },
  },
  native: {
    hello: ["Greetings", "Be welcome", "Welcome, neighbour"],
    yes: ["Yes", "Agreed", "It is so"],
    no: ["No", "We will not", "Never"],
    wow: ["Well done!", "A good day!", "That is good!"],
    ugh: ["Enough!", "This is wrong!", "Shameful!"],
    thanks: ["We thank you", "Thank you, friend"],
    bye: ["Until we meet again", "Travel well"],
    friend: ["friend", "neighbour", "cousin"],
    food: [
      "corn, beans and squash",
      "wild rice",
      "maple sugar",
      "venison stew",
      "cornbread",
    ],
    place: [
      "the river",
      "our homelands",
      "the valley",
      "the lakes",
      "the eastern woods",
      "our villages",
    ],
    lines: {
      idle: [
        "Plant corn, beans and squash together and each helps the others grow. Allies could learn from that.",
        "We have traded on these waters for a thousand years. We can wait.",
        "An alliance must be kept, not just signed.",
        "Our council has met. We will decide together, as we always have.",
        "Think seven generations ahead, the old teaching says. Do you?",
        "The river feeds everyone. Do not foul it.",
      ],
      attacked: [
        "{name}, our council has spoken: this land is not yours to take.",
        "We remember every treaty, {name}. Including the ones broken.",
      ],
      allianceAccepted: [
        "We will keep this agreement, {name}. See that you do too.",
      ],
      betrayed: ["Another broken promise, {name}. We have seen this before."],
      allianceOffer: [
        "{name}, our council invites you to talk. Will you come in good faith?",
      ],
    },
  },
  arctic: {
    hello: ["Hello", "Greetings", "Welcome"],
    wow: ["Wonderful!", "A good catch!", "Beautiful!"],
    ugh: ["Brr!", "Oh no!"],
    food: ["smoked fish", "seal stew", "bannock", "dried char", "berries"],
    place: [
      "the tundra",
      "the sea ice",
      "the northern lights",
      "the long night",
      "the coast",
    ],
    lines: {
      idle: [
        "The sun won't set for two months. Plenty of daylight to fight in.",
        "The ice is thick today. Good travelling.",
        "Out here, everyone helps everyone or nobody makes it through winter.",
      ],
    },
  },
  medieval: {
    hello: ["Hail", "Well met", "Greetings"],
    yes: ["Aye", "Yea"],
    no: ["Nay", "Never"],
    wow: ["Wassail!", "Huzzah!", "Glorious!"],
    ugh: ["By the saints!", "Alas!", "Woe!"],
    thanks: ["My thanks", "I thank thee"],
    bye: ["Fare thee well", "God keep thee"],
    friend: ["kinsman", "good friend"],
    food: ["mead", "barley bread", "roast boar", "honey cakes", "pottage"],
    place: [
      "the mead hall",
      "the great hall",
      "the old fort",
      "the river ford",
    ],
    lines: {
      idle: [
        "The bard has started another song about me. It is very long.",
        "Shield wall at dawn. Mead hall at dusk.",
        "The monks are writing all this down. Look heroic.",
      ],
      attacked: ["{name}! Raise the shield wall!"],
    },
  },
  pirate: {
    hello: ["Ahoy", "Ahoy there"],
    yes: ["Aye", "Aye aye"],
    no: ["Nay", "Belay that"],
    wow: ["Yo ho ho!", "Shiver me timbers!", "Huzzah!"],
    ugh: ["Blimey!", "Blast!", "Barnacles!"],
    thanks: ["Much obliged", "My thanks"],
    bye: ["Fair winds", "Farewell"],
    friend: ["matey", "me hearty"],
    food: ["grog", "hardtack", "salted pork", "coconuts", "limes"],
    place: [
      "Tortuga",
      "the Spanish Main",
      "the high seas",
      "Nassau",
      "Davy Jones' locker",
    ],
    lines: {
      idle: [
        "Any merchant ships passing by? Asking for no particular reason.",
        "Dead men tell no tales. Neither do I.",
      ],
      attacked: ["{name}, you'll walk the plank for that!"],
    },
  },
  space: {
    hello: ["Greetings, Earthling", "Hello", "Greetings"],
    yes: ["Affirmative", "Confirmed"],
    no: ["Negative", "Request denied"],
    wow: ["Stellar!", "Out of this world!", "Cosmic!"],
    ugh: [
      "Houston, we have a problem!",
      "Oh, solar flares!",
      "Critical failure!",
    ],
    thanks: ["Thanks", "Transmission received, thanks"],
    bye: ["Over and out", "Safe orbits"],
    friend: ["fellow traveller"],
    food: [
      "freeze-dried ice cream",
      "hydroponic lettuce",
      "space tacos",
      "recycled water",
    ],
    place: [
      "the crater rim",
      "Olympus Mons",
      "the asteroid belt",
      "low orbit",
      "the dark side",
    ],
    lines: {
      idle: [
        "In low gravity my troops can jump twice as high. Useful.",
        "The view of Earth from here is lovely. Very small, though.",
        "Signal delay is twenty minutes. Please attack slowly.",
      ],
    },
  },
  north_pole: {
    hello: ["Ho ho ho", "Season's greetings"],
    wow: ["Ho ho ho!", "Jolly good!", "Merry!"],
    ugh: ["Oh, fiddlesticks!", "Oh, reindeer droppings!"],
    thanks: ["Thank you kindly"],
    bye: ["Merry everything"],
    food: ["milk and cookies", "candy canes", "gingerbread", "hot cocoa"],
    place: ["the North Pole", "the workshop", "the reindeer stables"],
    lines: {
      idle: ["I'm making a list. You're on it. Which list? We'll see."],
      attacked: ["{name}, that's a lump of coal for you this year!"],
    },
  },
};
