// LIFE (r11): the trades, offices of the law, lines of arms and crooked
// livings added to the colonies: smiths and coopers, ropewalks and
// shipyards, millers, brewers and distillers, fishermen and whalers,
// surveyors, schoolmasters, midwives and apothecaries, shopkeepers; native
// guides, go-betweens and counsellors; the watch, the militia and the
// thief-takers; and pickpockets, fences, smugglers, highwaymen, coiners and
// pirates. Plain data, read by the rulebook (LifeRules.ts), so it imports
// nothing but types.

import type {
  BackgroundDef,
  JobDef,
  PlaceDef,
  RankDef,
  RoleDef,
} from "./LifeRules";
import type {
  BackgroundId,
  JobKind,
  PlaceKind,
  R11BackgroundId,
  R11JobKind,
  RoleId,
} from "./Types";

/** What it takes before anyone will have you at a trade (or you can set up in it). */
export interface JobRequires {
  skills?: Partial<Record<import("./Types").Skill, number>>;
  /** A name in the underworld. */
  notoriety?: number;
  /** Only in a port town; only in the north (whaling grounds). */
  coastal?: boolean;
  north?: boolean;
  /**
   * People who'll vouch for you: the underworld (a den you know, a name, or
   * a crooked upbringing), the native peoples (born to them, or woods-wise
   * and travelled among them), or the sea (seamanship, or a sea upbringing).
   */
  contacts?: "underworld" | "natives" | "sea";
  /** Pirate waters in pirate years (or a name that draws the crews). */
  pirates?: boolean;
}

/** Kinds of work, for the register and the list of every trade. */
export type JobGroup =
  | "land"
  | "craft"
  | "sea"
  | "trade"
  | "learned"
  | "arms"
  | "law"
  | "crime"
  | "native";

export const JOB_GROUPS: { id: JobGroup; name: string; text: string }[] = [
  {
    id: "land",
    name: "The land",
    text: "Fields, woods and the beasts in them.",
  },
  {
    id: "craft",
    name: "Crafts",
    text: "Forge, bench, mill and vat: made by hand, sold by the piece.",
  },
  { id: "sea", name: "The sea", text: "Docks, decks, nets and harpoons." },
  {
    id: "trade",
    name: "Trade and taverns",
    text: "Buying, selling, pouring and lending.",
  },
  {
    id: "learned",
    name: "Learned and genteel",
    text: "Letters, physic, the pulpit, the law and the land office.",
  },
  { id: "arms", name: "Arms", text: "The army, the militia and the war path." },
  {
    id: "law",
    name: "The law",
    text: "The watch, the constables, the sheriff, and those who hunt for rewards.",
  },
  {
    id: "crime",
    name: "The wrong side of the law",
    text: "Quick money, a name in the underworld, and the rope at the end of it.",
  },
  {
    id: "native",
    name: "Your people's work",
    text: "The hunt, the fields, making, healing, trading and the council fire.",
  },
];

const rk = (
  title: string,
  wage: number,
  months: number,
  skill: number,
  renown: number,
  extra: Partial<RankDef> = {},
): RankDef => ({ title, wage, months, skill, renown, ...extra });

export const MORE_JOBS: Record<R11JobKind, JobDef> = {
  // ------------------------------------------------ crafts
  blacksmith: {
    name: "The forge",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Striker", 2, 0, 0, 0),
      rk("Journeyman smith", 3.8, 12, 6, 0),
      rk("Master smith", 6.5, 30, 10, 5, {
        buy: { cost: 35, what: "a forge of your own" },
      }),
      rk("Ironmaster", 10, 36, 13, 15),
    ],
    danger: 0.003,
    stress: 2,
    employer: "master",
    business: "forge",
    group: "craft",
    good: "Craft and a strong arm. Every farmer, carter and soldier comes to you: steady money, and burns.",
    text: "Horseshoes, nails, plough irons, musket locks and the odd gate. The forge never cools.",
  },
  cooper: {
    name: "The cooperage",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Apprentice cooper", 1.6, 0, 0, 0),
      rk("Journeyman cooper", 3.5, 18, 6, 0),
      rk("Master cooper", 6, 30, 10, 5, {
        buy: { cost: 25, what: "a cooperage of your own" },
      }),
      rk("Cooper to the fleet", 8.5, 36, 12, 12),
    ],
    danger: 0,
    stress: 1,
    employer: "master",
    business: "cooperage",
    group: "craft",
    good: "Craft, and the trade of every planter and ship's master: everything travels in a barrel.",
    text: "Staves, hoops and hogsheads for tobacco, rum, salt fish and flour. A tight barrel is a good name.",
  },
  tanner: {
    name: "The tanyard",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Tanner's boy", 1.8, 0, 0, 0),
      rk("Tanner", 3.6, 12, 6, 0),
      rk("Master tanner", 6, 30, 9, 4, {
        buy: { cost: 30, what: "a tanyard of your own" },
      }),
      rk("Leather merchant", 8.5, 36, 11, 10, { second: 8 }),
    ],
    danger: 0.003,
    stress: 3,
    employer: "master",
    business: "tanyard",
    group: "craft",
    good: "Craft and trade; good money in a smell nobody else will stand.",
    text: "Hides limed, scraped and soaked for a year in oak bark. Your neighbours will mention it.",
  },
  ropewalker: {
    name: "The ropewalk",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "seamanship",
    ranks: [
      rk("Spinner", 2, 0, 0, 0),
      rk("Ropemaker", 3.8, 12, 6, 0),
      rk("Ropewalk foreman", 6, 24, 9, 4, { second: 4 }),
      rk("Ropewalk owner", 9.5, 36, 11, 12, {
        buy: { cost: 60, what: "a ropewalk of your own" },
      }),
    ],
    danger: 0.002,
    stress: 2,
    employer: "master",
    business: "ropewalk",
    requires: { coastal: true },
    group: "craft",
    good: "Craft, and the shipmasters' custom: a port town can't do without you.",
    text: "Walking backwards a quarter mile at a time, spinning hemp into cable for the ships. Port towns only.",
  },
  shipwright: {
    name: "The shipyard",
    native: false,
    places: ["docks"],
    main: "craft",
    second: "seamanship",
    ranks: [
      rk("Yard apprentice", 1.8, 0, 0, 0),
      rk("Shipwright", 4.2, 18, 7, 0),
      rk("Master shipwright", 7.5, 30, 11, 8, { second: 5 }),
      rk("Shipbuilder", 12, 36, 13, 20, {
        buy: { cost: 120, what: "a shipyard of your own" },
      }),
    ],
    danger: 0.004,
    stress: 2,
    employer: "captain",
    business: "shipyard",
    group: "craft",
    good: "Craft and seamanship. Builders sell boats: your own comes cheaper, and every captain owes you.",
    text: "Keels laid, ribs raised, planks steamed and caulked. A sloop takes a winter; a ship, two.",
  },
  carpenter: {
    name: "Joinery",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Apprentice joiner", 1.5, 0, 0, 0),
      rk("Carpenter", 3.5, 12, 6, 0),
      rk("Master builder", 6.5, 30, 10, 6, {
        buy: { cost: 25, what: "a joiner's shop of your own" },
      }),
      rk("Housewright", 9, 36, 12, 14),
    ],
    danger: 0.002,
    stress: 1,
    employer: "master",
    business: "joiner's shop",
    group: "craft",
    good: "Craft; houses, barns and churches go up under your hands, and their owners remember.",
    text: "Frames raised, floors laid, a chest of drawers for the minister's wife.",
  },
  miller: {
    name: "The mill",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Miller's man", 2.2, 0, 0, 0),
      rk("Miller", 4.5, 18, 7, 2, {
        buy: { cost: 45, what: "a gristmill of your own" },
      }),
      rk("Mill master", 8, 36, 10, 10),
    ],
    danger: 0.002,
    stress: 1,
    employer: "master",
    business: "gristmill",
    group: "craft",
    good: "Craft and trade. Every farmer brings you grain and pays a toll of it; nobody quite trusts a miller.",
    text: "Millstones dressed, the race cleared, the toll dish taken from every sack.",
  },
  brewer: {
    name: "The brewhouse",
    native: false,
    places: ["tavern"],
    main: "craft",
    second: "persuasion",
    ranks: [
      rk("Brewer's boy", 1.8, 0, 0, 0),
      rk("Brewer", 4, 12, 6, 0),
      rk("Master brewer", 7, 30, 10, 6, {
        buy: { cost: 40, what: "a brewhouse of your own" },
      }),
    ],
    danger: 0,
    stress: 1,
    employer: "innkeeper",
    business: "brewhouse",
    group: "craft",
    good: "Craft; the tavern crowd knows you, and everyone drinks.",
    text: "Malt, hops (or spruce, or pumpkin) and a good copper. Small beer for breakfast, strong for the evening.",
  },
  distiller: {
    name: "The still",
    native: false,
    places: ["workshop"],
    main: "craft",
    second: "trade",
    ranks: [
      rk("Still-hand", 2, 0, 0, 0),
      rk("Distiller", 4.5, 18, 7, 0),
      rk("Master distiller", 7.5, 30, 10, 8, {
        buy: { cost: 60, what: "a distillery of your own" },
      }),
      rk("Rum merchant", 11, 36, 12, 15, { second: 8 }),
    ],
    danger: 0.004,
    stress: 2,
    employer: "master",
    business: "distillery",
    group: "craft",
    good: "Craft and trade; rum is money in every port, and in the woods.",
    text: "Molasses into rum by the coast, rye into whiskey in the backcountry. Mind the fire.",
  },
  // ------------------------------------------------ the sea
  fisherman: {
    name: "Fishing",
    native: false,
    places: ["docks"],
    main: "seamanship",
    second: "trade",
    ranks: [
      rk("Fisherman's boy", 1.8, 0, 0, 0),
      rk("Fisherman", 3.5, 12, 5, 0),
      rk("Skipper", 6, 24, 8, 3, {
        buy: { cost: 18, what: "a shallop of your own" },
      }),
      rk("Fishing master", 9, 36, 11, 10),
    ],
    danger: 0.012,
    stress: 2,
    employer: "captain",
    selfStart: true,
    business: "fishing shallop",
    post: "sea",
    group: "sea",
    good: "Seamanship; cod and mackerel always sell. Anyone with a boat may fish: a boat of your own pays best.",
    text: "Hand lines on the banks, nets in the bay, and the catch salted and dried on flakes ashore.",
  },
  whaler: {
    name: "Whaling",
    native: false,
    places: ["docks"],
    main: "seamanship",
    second: "fighting",
    ranks: [
      rk("Greenhand", 2.4, 0, 0, 0),
      rk("Boatsteerer", 4.5, 12, 7, 2),
      rk("Mate", 7.5, 24, 10, 6, { second: 6 }),
      rk("Whaling master", 12, 36, 12, 18, {
        buy: { cost: 100, what: "a whaler of your own" },
      }),
    ],
    danger: 0.02,
    stress: 3,
    employer: "captain",
    post: "sea",
    requires: { coastal: true, north: true },
    group: "sea",
    good: "Seamanship and nerve; whale oil lights the world, and a good voyage makes a fortune. Some don't come back.",
    text: 'Lookouts on the dunes, a cry of "there she blows", and the boats away. Northern ports only.',
  },
  // ------------------------------------------------ learned
  surveyor: {
    name: "The land office",
    native: false,
    places: ["governor"],
    main: "letters",
    second: "woodcraft",
    ranks: [
      rk("Chain-bearer", 2.2, 0, 0, 0),
      rk("Deputy surveyor", 4.5, 12, 6, 0, { second: 4 }),
      rk("County surveyor", 7.5, 24, 9, 8, { second: 6 }),
      rk("Surveyor-general", 12, 36, 12, 20, { opinion: 25 }),
    ],
    danger: 0.006,
    stress: 2,
    need: { letters: 3 },
    ownNation: true,
    employer: "official",
    fame: 0.3,
    group: "learned",
    good: "Letters and woodcraft. You see the land first: the gentry court you, and the best lots are known to you.",
    text: "Chain, compass and a long walk through the woods, then a plat drawn up in fair ink. A young Washington started here.",
  },
  schoolmaster: {
    name: "The school",
    native: false,
    places: ["church"],
    main: "letters",
    second: "persuasion",
    ranks: [
      rk("Usher", 1.8, 0, 0, 0),
      rk("Schoolmaster", 3.5, 12, 6, 2),
      rk("Grammar master", 5.5, 24, 9, 6),
      rk("Rector of the academy", 8.5, 36, 12, 15),
    ],
    danger: 0,
    stress: 2,
    need: { letters: 4 },
    employer: "preacher",
    fame: 0.3,
    group: "learned",
    good: "Letters and persuasion. Poor pay but respect, and the town's children grow up knowing your name.",
    text: "Hornbooks, the catechism, Latin for the bright ones and the birch for the rest.",
  },
  midwife: {
    name: "Midwifery",
    native: false,
    places: ["apothecary"],
    main: "medicine",
    second: "persuasion",
    ranks: [
      rk("Midwife's helper", 1.5, 0, 0, 0),
      rk("Midwife", 3.5, 18, 6, 3),
      rk("Licensed midwife", 5.5, 30, 9, 8),
      rk("Matron", 7.5, 36, 11, 14),
    ],
    danger: 0.003,
    stress: 2,
    employer: "physician",
    selfStart: true,
    requires: { skills: { medicine: 5 } },
    group: "learned",
    good: "Medicine; every family in town owes you a child, and every secret is yours.",
    text: "Called out at all hours to bring the town's children into it. Most midwives are women; a few are men.",
  },
  apothecary: {
    name: "The apothecary's",
    native: false,
    places: ["apothecary"],
    main: "medicine",
    second: "trade",
    ranks: [
      rk("Apprentice apothecary", 1.6, 0, 0, 0),
      rk("Apothecary", 4, 18, 7, 0),
      rk("Master apothecary", 7, 30, 10, 8, {
        buy: { cost: 45, what: "an apothecary's shop of your own" },
      }),
      rk("Druggist to the colony", 10, 36, 12, 16),
    ],
    danger: 0.002,
    stress: 1,
    need: { letters: 2 },
    employer: "physician",
    business: "apothecary's shop",
    group: "learned",
    good: "Medicine and trade: Jesuit's bark, laudanum and theriac, sold dear.",
    text: "Simples ground, pills rolled, and drugs from London sold to physicians and the desperate.",
  },
  // ------------------------------------------------ trade
  shopkeeper: {
    name: "The shop",
    native: false,
    places: ["market"],
    main: "trade",
    second: "persuasion",
    ranks: [
      rk("Shop boy", 1.8, 0, 0, 0),
      rk("Shopkeeper", 4, 12, 6, 0),
      rk("Storekeeper", 6.5, 24, 9, 4, {
        buy: { cost: 40, what: "a store of your own" },
      }),
      rk("Wholesale merchant", 10, 36, 12, 14),
    ],
    danger: 0,
    stress: 2,
    employer: "merchant",
    business: "store",
    group: "trade",
    good: "Trade and persuasion; everyone owes you on the books, and you hear everything.",
    text: "Pins, cloth, tea, powder and shot, sold on credit until the harvest comes in.",
  },
  // ------------------------------------------------ native peoples and the frontier
  interpreter: {
    name: "Speaking between peoples",
    native: null,
    places: ["councilfire", "governor"],
    main: "persuasion",
    second: "letters",
    ranks: [
      rk("Go-between", 2, 0, 0, 0),
      rk("Interpreter", 4, 12, 7, 3),
      rk("Sworn interpreter", 6.5, 24, 10, 10),
      rk("Agent to the nations", 10, 36, 12, 20, { opinion: 25 }),
    ],
    danger: 0.004,
    stress: 2,
    employer: "sachem",
    requires: { skills: { persuasion: 4 }, contacts: "natives" },
    fame: 0.4,
    group: "native",
    good: "Persuasion, and trust on both sides: treaties, trade and wars turn on your words.",
    text: "Carrying words between the council fire and the governor's house, and making sure they mean the same at both ends.",
  },
  guide: {
    name: "Guiding",
    native: null,
    places: ["woods"],
    main: "woodcraft",
    second: "fighting",
    ranks: [
      rk("Guide", 2.5, 0, 0, 0),
      rk("Trusted guide", 4, 12, 7, 2),
      rk("Scout", 6, 24, 10, 8, { second: 5 }),
      rk("Chief of scouts", 9, 36, 12, 16, { second: 8 }),
    ],
    danger: 0.008,
    stress: 1,
    employer: "hunter",
    selfStart: true,
    requires: { skills: { woodcraft: 5 } },
    post: "anywhere",
    fame: 0.2,
    group: "native",
    good: "Woodcraft. Paid to lead traders, surveyors and armies through country only you know; your own journeys go quicker and safer.",
    text: "The trails, the fords, the portages and who is friendly this year. You work wherever you walk.",
  },
  counsellor: {
    name: "The sachem's counsel",
    native: true,
    places: ["councilfire"],
    main: "persuasion",
    second: "leadership",
    ranks: [
      rk("Pipe-bearer", 1.5, 0, 0, 0),
      rk("Counsellor", 3.5, 18, 8, 10),
      rk("Elder counsellor", 6, 36, 11, 25, { opinion: 30 }),
      rk("Principal counsellor", 8.5, 36, 13, 40, { opinion: 45 }),
    ],
    danger: 0,
    stress: 2,
    need: { persuasion: 5 },
    employer: "sachem",
    fame: 0.4,
    group: "native",
    good: "Persuasion and leadership; you speak in the sachem's ear, and some day for the nation.",
    text: "Sitting with the sachem, remembering the old treaties and the old grudges, and choosing words with care.",
  },
  // ------------------------------------------------ the law and arms
  watch: {
    name: "The watch and the law",
    native: false,
    places: ["gaol"],
    main: "fighting",
    second: "persuasion",
    ranks: [
      rk("Watchman", 2, 0, 0, 0),
      rk("Constable", 3.8, 12, 6, 2),
      rk("High constable", 5.5, 24, 8, 8, { second: 5 }),
      rk("Under-sheriff", 8, 24, 9, 15, { second: 7, opinion: 20 }),
      rk("Sheriff", 12, 30, 10, 25, { second: 9, commission: true }),
      rk("High sheriff", 16, 36, 11, 40, { second: 11, commission: true }),
    ],
    danger: 0.006,
    stress: 2,
    ownNation: true,
    employer: "constable",
    selfStart: true,
    law: true,
    fame: 0.3,
    group: "law",
    good: "Fighting and persuasion. You know every rogue in town, take them up, and are offered bribes to look away.",
    text: "Lantern, staff and rattle by night; warrants, the stocks and the gaol by day. Sheriffs are named by the governor.",
  },
  militia: {
    name: "The militia",
    native: false,
    places: ["fort", "tavern"],
    main: "fighting",
    second: "leadership",
    ranks: [
      rk("Private", 1.8, 0, 0, 0),
      rk("Corporal", 2.6, 8, 5, 0),
      rk("Sergeant", 3.6, 16, 7, 2, { second: 4 }),
      rk("Ensign", 5, 18, 8, 6, { second: 5, commission: true }),
      rk("Lieutenant", 6.5, 18, 9, 10, { second: 6, commission: true }),
      rk("Captain", 8.5, 24, 10, 16, { second: 8, commission: true }),
      rk("Major", 11, 30, 11, 26, { second: 10, commission: true }),
      rk("Colonel", 14, 30, 12, 38, { second: 12, commission: true }),
    ],
    danger: 0.006,
    stress: 1,
    ownNation: true,
    employer: "sergeant",
    selfStart: true,
    fame: 0.25,
    group: "arms",
    good: "Fighting and leadership close to home. Captains may raise a company of their own and lead it on campaign.",
    text: "Musters on the green, watches on the frontier, and turning out when the drums beat. Enrol at the muster (the tavern or the fort).",
  },
  thieftaker: {
    name: "Thief-taking",
    native: false,
    places: ["gaol"],
    main: "fighting",
    second: "stealth",
    ranks: [
      rk("Thief-taker", 2.5, 0, 0, 0),
      rk("Bounty hunter", 4.5, 12, 7, 4, { second: 5 }),
      rk("Thief-taker general", 8, 30, 10, 15, { second: 8 }),
    ],
    danger: 0.012,
    stress: 2,
    employer: "constable",
    selfStart: true,
    requires: { skills: { fighting: 4 } },
    law: true,
    fame: 0.2,
    group: "law",
    good: "Fighting and stealth. Rewards for rogues taken alive (mostly); the underworld hates you, the law needs you.",
    text: "Posted rewards, a pair of irons and a long memory for faces. Paid by the head, not the month.",
  },
  // ------------------------------------------------ the wrong side of the law
  thief: {
    name: "Thieving",
    native: false,
    places: ["den", "market"],
    main: "stealth",
    second: "persuasion",
    ranks: [
      rk("Pickpocket", 2.4, 0, 0, 0),
      rk("Cutpurse", 3.6, 8, 6, 0, { notoriety: 5 }),
      rk("Housebreaker", 5.5, 18, 8, 0, { second: 5, notoriety: 15 }),
      rk("Master thief", 8, 24, 10, 0, { second: 7, notoriety: 30 }),
      rk("Gang boss", 12, 30, 11, 0, { second: 9, notoriety: 50 }),
    ],
    danger: 0.006,
    stress: 3,
    employer: "fence",
    selfStart: true,
    crime: { grade: 1, heat: 0.5 },
    group: "crime",
    good: "Stealth. Quick money, and a name in the underworld that opens the den. The watch is always looking.",
    text: "A crowded market and a careless pocket; later, windows, shutters and strongboxes. Gang bosses run a band of their own.",
  },
  fence: {
    name: "Fencing",
    native: false,
    places: ["den"],
    main: "trade",
    second: "stealth",
    ranks: [
      rk("Receiver", 2.6, 0, 0, 0),
      rk("Fence", 5, 18, 7, 0, { notoriety: 20 }),
      rk("Master fence", 8, 30, 10, 0, {
        notoriety: 40,
        buy: { cost: 60, what: "a pawnshop for a front" },
      }),
      rk("Kingpin", 13, 36, 12, 0, { second: 9, notoriety: 65 }),
    ],
    danger: 0.003,
    stress: 2,
    employer: "fence",
    selfStart: true,
    requires: { contacts: "underworld", notoriety: 10 },
    crime: { grade: 1, heat: 0.25 },
    group: "crime",
    good: "Trade and stealth. Thieves bring you what they take; you sell it on at a profit and keep their secrets.",
    text: "Silver spoons melted, watches sent to another colony, cloth re-dyed. No questions; good prices for you.",
  },
  smuggler: {
    name: "Free trading",
    native: false,
    places: ["docks"],
    main: "seamanship",
    second: "stealth",
    ranks: [
      rk("Runner", 2.6, 0, 0, 0),
      rk("Smuggler", 4.6, 12, 6, 0, { notoriety: 5 }),
      rk("Free trader", 7.5, 24, 9, 0, {
        second: 6,
        notoriety: 15,
        buy: { cost: 40, what: "a share in a smuggling sloop" },
      }),
      rk("Smuggling master", 11, 36, 11, 0, { notoriety: 35 }),
    ],
    danger: 0.01,
    stress: 2,
    selfStart: true,
    requires: { contacts: "underworld" },
    crime: { grade: 1, heat: 0.3 },
    post: "sea",
    group: "crime",
    good: "Seamanship and stealth. Molasses without the duty, Dutch tea, French brandy: half the merchants do it, and the customs men are paid to be blind.",
    text: "Night landings in quiet coves and a false manifest for the customs house.",
  },
  highwayman: {
    name: "The road",
    native: false,
    places: ["tavern", "woods"],
    main: "fighting",
    second: "stealth",
    ranks: [
      rk("Footpad", 2.6, 0, 0, 0),
      rk("Highwayman", 5, 12, 7, 0, { notoriety: 15, kit: "horse" }),
      rk("Gentleman of the road", 8, 24, 9, 0, { second: 7, notoriety: 35 }),
      rk("Captain of the road", 12, 30, 11, 0, { second: 9, notoriety: 55 }),
    ],
    danger: 0.02,
    stress: 3,
    selfStart: true,
    requires: { skills: { fighting: 4 } },
    crime: { grade: 3, heat: 0.8 },
    post: "road",
    group: "crime",
    good: 'Fighting and stealth. "Stand and deliver": rich pickings, ballads sung about you, and a hanging matter.',
    text: "Coaches, post riders and drovers coming home from market. A highwayman needs a horse; a footpad, good legs.",
  },
  counterfeiter: {
    name: "Coining and forging",
    native: false,
    places: ["den"],
    main: "craft",
    second: "letters",
    ranks: [
      rk("Utterer", 2.5, 0, 0, 0),
      rk("Coiner", 5, 18, 7, 0, { notoriety: 10 }),
      rk("Forger", 8, 24, 10, 0, { second: 6, notoriety: 25 }),
      rk("Master forger", 12, 36, 12, 0, { second: 9, notoriety: 45 }),
    ],
    danger: 0.004,
    stress: 3,
    employer: "fence",
    selfStart: true,
    requires: { contacts: "underworld" },
    crime: { grade: 3, heat: 0.45 },
    group: "crime",
    good: 'Craft and letters. Clipped coin, pewter dollars and forged bills of credit: "To counterfeit is death", the bills say.',
    text: "First you pass bad money; then you make it. Forgers of the colonies' paper money are hanged when caught.",
  },
  pirate: {
    name: "Piracy",
    native: null,
    places: ["docks"],
    main: "seamanship",
    second: "fighting",
    ranks: [
      rk("Pirate", 3, 0, 0, 0),
      rk("Able pirate", 4.5, 8, 6, 0, { notoriety: 10 }),
      rk("Quartermaster", 7, 18, 9, 0, { second: 7, notoriety: 30 }),
      rk("Pirate captain", 12, 24, 11, 0, { second: 9, notoriety: 50 }),
      rk("Pirate commodore", 18, 36, 13, 0, { second: 11, notoriety: 75 }),
    ],
    danger: 0.03,
    stress: 3,
    selfStart: true,
    requires: { contacts: "sea", pirates: true },
    crime: { grade: 3, heat: 0.7 },
    post: "sea",
    group: "crime",
    good: "Seamanship and fighting. Shares of every prize, a vote on the captain, and a gibbet at the harbour mouth if it ends badly.",
    text: "On the account: under the black flag out of Nassau, the Carolina inlets or the islands. Rich in the golden age (1650 to 1730), thin before and after.",
  },
};

/** Who takes people on for the new trades, beyond the old ones. */
export const MORE_ROLE_JOBS: Partial<Record<RoleId, JobKind[]>> = {
  master: [
    "blacksmith",
    "cooper",
    "tanner",
    "ropewalker",
    "carpenter",
    "miller",
    "distiller",
  ],
  innkeeper: ["brewer"],
  captain: ["fisherman", "whaler", "shipwright"],
  merchant: ["shopkeeper"],
  physician: ["apothecary", "midwife"],
  preacher: ["schoolmaster"],
  official: ["surveyor", "interpreter"],
  sachem: ["counsellor", "interpreter"],
  sergeant: ["militia"],
  hunter: ["guide"],
};

export const MORE_ROLES: Record<"constable" | "fence", RoleDef> = {
  constable: {
    jobs: ["watch", "thieftaker"],
    doing: [
      "at the watch-house",
      "writing up a warrant",
      "seeing to the prisoners",
      "on his rounds",
    ],
    title: "High constable",
    native: false,
    place: "gaol",
    job: "watch",
    skill: "fighting",
    status: 3,
    wealth: 20,
    becomes: ["watch", 2],
  },
  fence: {
    jobs: ["thief", "fence", "counterfeiter"],
    doing: [
      "weighing silver",
      "behind the curtain",
      "counting watches",
      "listening",
    ],
    title: "Fence",
    native: false,
    place: "den",
    job: "thief",
    skill: "stealth",
    status: 2,
    wealth: 45,
    becomes: ["fence", 1],
  },
};

export const MORE_PLACES: Record<"gaol" | "den", PlaceDef> = {
  gaol: {
    name: "The watch-house",
    text: "The constable's lantern, the stocks and pillory outside, and the gaol behind. The law of the town lives here.",
  },
  den: {
    name: "The den",
    text: "A back room behind a sailors' tavern: cards, stolen silver, and nobody's real name. Only those who know find it.",
  },
};

/** The groups the old trades belong to. */
const OLD_GROUPS: Partial<Record<JobKind, JobGroup>> = {
  farmer: "land",
  servant: "land",
  trapper: "land",
  millhand: "craft",
  craftsman: "craft",
  newsman: "learned",
  soldier: "arms",
  sailor: "sea",
  clerk: "trade",
  innkeeper: "trade",
  official: "learned",
  law: "learned",
  preacher: "learned",
  physician: "learned",
  hunter: "native",
  warrior: "native",
  grower: "native",
  healer: "native",
  trader: "native",
  speaker: "native",
  maker: "native",
};

export function jobGroupOf(kind: JobKind, def: JobDef): JobGroup {
  return def.group ?? OLD_GROUPS[kind] ?? "craft";
}

/** Where the work is, said simply. */
export const PLACE_WORDS: Partial<Record<PlaceKind, string>> = {
  gaol: "the watch-house",
  den: "the den",
};

// ---------------------------------------------------------------- backgrounds

export const MORE_BACKGROUNDS: Record<R11BackgroundId, BackgroundDef> = {
  blacksmith: {
    name: "Smith's striker",
    native: false,
    blurb: "Sparks, sweat and a hammer twice your weight.",
    text: "Starts striking at the forge. Journeyman, master, and a forge of your own.",
    skills: { craft: 5, fighting: 2, trade: 1 },
    purse: 10,
    job: "blacksmith",
    renown: 0,
    lifestyle: "modest",
  },
  cooper: {
    name: "Cooper's apprentice",
    native: false,
    blurb: "Staves, hoops and a good ear for a tight barrel.",
    text: "Starts at the cooperage. Every planter and shipmaster needs barrels.",
    skills: { craft: 5, trade: 2, seamanship: 1 },
    purse: 10,
    job: "cooper",
    renown: 0,
    lifestyle: "modest",
  },
  tanner: {
    name: "Tanner's boy",
    native: false,
    blurb: "Bark pits, hides and a smell that follows you home.",
    text: "Starts in the tanyard. Good money, few visitors.",
    skills: { craft: 4, trade: 2, farming: 1, woodcraft: 1 },
    purse: 11,
    job: "tanner",
    renown: 0,
    lifestyle: "modest",
  },
  ropewalker: {
    name: "Ropewalk spinner",
    native: false,
    blurb: "A quarter mile backwards, twice a day.",
    text: "Starts spinning at a port's ropewalk (if home is a port). Foreman, then a ropewalk of your own.",
    skills: { craft: 4, seamanship: 2, fighting: 1 },
    purse: 9,
    job: "ropewalker",
    renown: 0,
    lifestyle: "modest",
  },
  shipwright: {
    name: "Shipyard apprentice",
    native: false,
    blurb: "Adze, auger and oakum.",
    text: "Starts at the shipyard (if home has docks). Builders sell boats, and their own come cheap.",
    skills: { craft: 5, seamanship: 2 },
    purse: 9,
    job: "shipwright",
    renown: 0,
    lifestyle: "modest",
  },
  carpenter: {
    name: "Joiner's apprentice",
    native: false,
    blurb: "Mortise, tenon and a straight eye.",
    text: "Starts with a master joiner. Houses, barns and church pews.",
    skills: { craft: 5, trade: 1, woodcraft: 1 },
    purse: 10,
    job: "carpenter",
    renown: 0,
    lifestyle: "modest",
  },
  miller: {
    name: "Miller's man",
    native: false,
    blurb: "Flour in your hair and the toll dish in your hand.",
    text: "Starts at the gristmill. Millers do well, and are trusted less.",
    skills: { craft: 3, trade: 3, farming: 2 },
    purse: 12,
    job: "miller",
    renown: 0,
    lifestyle: "modest",
  },
  brewer: {
    name: "Brewer's boy",
    native: false,
    blurb: "Malt, hops and the tavern's back room.",
    text: "Starts brewing for the tavern. Everyone drinks.",
    skills: { craft: 4, persuasion: 2, trade: 1 },
    purse: 9,
    job: "brewer",
    renown: 0,
    lifestyle: "modest",
  },
  distiller: {
    name: "Still-hand",
    native: false,
    blurb: "Molasses, copper and a little fire.",
    text: "Starts at a still. Rum is money in every port.",
    skills: { craft: 4, trade: 3 },
    purse: 11,
    job: "distiller",
    renown: 0,
    lifestyle: "modest",
  },
  fisherman: {
    name: "Fisherman's boy",
    native: false,
    blurb: "Cod lines, salt and cold hands.",
    text: "Starts fishing out of a port (if home has docks). Buy a boat, and you're your own skipper.",
    skills: { seamanship: 5, trade: 1, woodcraft: 1 },
    purse: 8,
    job: "fisherman",
    renown: 0,
    lifestyle: "frugal",
  },
  whaler: {
    name: "Greenhand",
    native: false,
    blurb: "Off the island in a whaleboat, with a harpoon you've never thrown.",
    text: "Starts as a greenhand on a northern whaler (if home is a northern port). Rich voyages and lost boats.",
    skills: { seamanship: 4, fighting: 2, trade: 1 },
    purse: 8,
    job: "whaler",
    renown: 0,
    lifestyle: "frugal",
  },
  surveyor: {
    name: "Chain-bearer",
    native: false,
    blurb: "Sixty-six feet of chain and a gentleman's compass.",
    text: "Starts carrying the chain for the colony's surveyor (at the governor's house). The land office makes men rich.",
    skills: { letters: 4, woodcraft: 3, trade: 1 },
    purse: 12,
    job: "surveyor",
    renown: 1,
    lifestyle: "modest",
  },
  schoolmaster: {
    name: "Usher",
    native: false,
    blurb: "Hornbooks, catechism and a birch rod.",
    text: "Starts assisting the schoolmaster (at the church). Poor pay, good name.",
    skills: { letters: 5, persuasion: 2, faith: 1 },
    purse: 6,
    job: "schoolmaster",
    renown: 2,
    lifestyle: "frugal",
  },
  midwife: {
    name: "Midwife's helper",
    native: false,
    blurb: "Hot water, clean linen and steady hands.",
    text: "Starts helping at births (at the apothecary). Every family will owe you.",
    skills: { medicine: 5, persuasion: 2, faith: 1 },
    purse: 7,
    job: "midwife",
    renown: 1,
    lifestyle: "modest",
  },
  apothecary: {
    name: "Apothecary's apprentice",
    native: false,
    blurb: "Mortar, pestle and Latin labels.",
    text: "Starts at the apothecary's. Physic sold dear.",
    skills: { medicine: 4, trade: 2, letters: 2 },
    purse: 10,
    job: "apothecary",
    renown: 1,
    lifestyle: "modest",
  },
  shopkeeper: {
    name: "Shop boy",
    native: false,
    blurb: "Pins, tea, powder and shot, on credit.",
    text: "Starts behind the counter of a merchant's shop. A store of your own in time.",
    skills: { trade: 4, persuasion: 2, letters: 2 },
    purse: 12,
    job: "shopkeeper",
    renown: 0,
    lifestyle: "modest",
  },
  tapster: {
    name: "Tapster",
    native: false,
    blurb: "Pots, barrels and every rumour in town.",
    text: "Starts drawing ale at the tavern. Innkeeper, then the house is yours.",
    skills: { trade: 3, persuasion: 3, stealth: 1 },
    purse: 9,
    job: "innkeeper",
    renown: 0,
    lifestyle: "modest",
  },
  watchman: {
    name: "Watchman",
    native: false,
    blurb: "Lantern, staff and \"twelve o'clock and all's well\".",
    text: "Starts on the night watch (in a town with a watch-house). Constable, high constable, sheriff.",
    skills: { fighting: 4, persuasion: 2, stealth: 1 },
    purse: 8,
    job: "watch",
    renown: 1,
    lifestyle: "modest",
  },
  militiaman: {
    name: "Militiaman",
    native: false,
    blurb:
      "Every able man from sixteen to sixty, on the green with his musket.",
    text: "Starts in the militia. Commissions from the governor; captains raise companies of their own.",
    skills: { fighting: 4, leadership: 2, woodcraft: 1 },
    purse: 9,
    job: "militia",
    renown: 1,
    lifestyle: "modest",
  },
  thieftaker: {
    name: "Thief-taker",
    native: false,
    blurb: "Irons, a cudgel and a list of names.",
    text: "Starts hunting rewards (at the watch-house). Rogues taken up pay; rogues that get away remember.",
    skills: { fighting: 4, stealth: 2, persuasion: 1 },
    purse: 8,
    job: "thieftaker",
    renown: 0,
    lifestyle: "modest",
  },
  pickpocket: {
    name: "Street thief",
    native: false,
    blurb: "Quick fingers, quicker feet, and nobody's child.",
    text: "Starts picking pockets, and knows the den at home. Cutpurse, housebreaker, gang boss, or the gallows. Hard lives teach: 2 more skill points.",
    skills: { stealth: 5, persuasion: 1, fighting: 1 },
    purse: 4,
    job: "thief",
    renown: 0,
    lifestyle: "frugal",
    bonusPoints: 2,
    notoriety: 5,
  },
  smuggler: {
    name: "Smuggler's runner",
    native: false,
    blurb: "Lanterns in the cove, kegs up the cliff path.",
    text: "Starts running contraband (if home has docks), and knows the den. Free trader, then master of your own runs.",
    skills: { seamanship: 3, stealth: 3, trade: 1 },
    purse: 8,
    job: "smuggler",
    renown: 0,
    lifestyle: "modest",
    notoriety: 5,
  },
  footpad: {
    name: "Footpad",
    native: false,
    blurb: "A cudgel, a dark lane and a coach that comes by at dusk.",
    text: "Starts robbing travellers on foot. A horse makes you a highwayman. A hanging matter from the first purse.",
    skills: { fighting: 4, stealth: 3 },
    purse: 6,
    job: "highwayman",
    renown: 0,
    lifestyle: "frugal",
    notoriety: 8,
  },
  coiner: {
    name: "Coiner's boy",
    native: false,
    blurb: "Pewter, plaster moulds and nerve at the counter.",
    text: "Starts passing bad money for a coiner, and knows the den. Coiner, forger, master forger.",
    skills: { craft: 3, letters: 2, stealth: 2 },
    purse: 7,
    job: "counterfeiter",
    renown: 0,
    lifestyle: "frugal",
    notoriety: 5,
  },
  pirate: {
    name: "Pirate",
    native: false,
    blurb: "Signed the articles, under the black flag.",
    text: "Starts on the account out of a port (best in the islands and the Carolinas, 1650 to 1730). Shares of every prize, and a price on your head.",
    skills: { seamanship: 4, fighting: 3 },
    purse: 6,
    job: "pirate",
    renown: 0,
    lifestyle: "frugal",
    notoriety: 15,
  },
  guide: {
    name: "Guide",
    native: true,
    blurb: "The trails, the fords and who is friendly this year.",
    text: "Starts guiding travellers and traders through your country. Scouts are wanted in every war.",
    skills: { woodcraft: 5, fighting: 2, persuasion: 1 },
    purse: 5,
    job: "guide",
    renown: 1,
    lifestyle: "modest",
  },
  interpreter: {
    name: "Go-between",
    native: true,
    blurb: "Two tongues, two peoples, and neither quite trusts you.",
    text: "Starts carrying words between the council fire and the colonists. Interpreter, then agent to the nations.",
    skills: { persuasion: 5, letters: 1, trade: 2 },
    purse: 6,
    job: "interpreter",
    renown: 2,
    lifestyle: "modest",
  },
};

/** The group a background is listed under in the register. */
export function backgroundGroup(
  b: BackgroundId,
  bg: BackgroundDef,
  jobs: Record<JobKind, JobDef>,
): JobGroup {
  if (bg.native) return "native";
  if (b === "gentry") return "learned";
  return bg.job ? jobGroupOf(bg.job, jobs[bg.job]) : "learned";
}
