// Names for the colonists the game makes up, by culture, and the titles
// native nations' leaders went by.

interface NameList {
  male: string[];
  female: string[];
  family: string[];
}

export const NAMES: Record<string, NameList> = {
  english: {
    male: [
      "John",
      "Thomas",
      "William",
      "Richard",
      "Edward",
      "Henry",
      "George",
      "Robert",
      "Samuel",
      "Nathaniel",
      "Francis",
      "Christopher",
      "Edmund",
      "Gabriel",
      "Bartholomew",
      "Walter",
      "Ralph",
      "Miles",
      "Josias",
      "Anthony",
    ],
    female: [
      "Mary",
      "Elizabeth",
      "Anne",
      "Margaret",
      "Alice",
      "Joan",
      "Agnes",
      "Frances",
      "Susanna",
      "Dorothy",
      "Katherine",
      "Temperance",
      "Cicely",
      "Jane",
      "Sarah",
      "Grace",
    ],
    family: [
      "Smith",
      "Rolfe",
      "Gates",
      "Dale",
      "Percy",
      "West",
      "Wingfield",
      "Archer",
      "Martin",
      "Gosnold",
      "Yeardley",
      "Pierce",
      "Bennett",
      "Harrison",
      "Byrd",
      "Carter",
      "Ludwell",
      "Spelman",
      "Pory",
      "Claiborne",
      "Mathews",
      "Fleet",
    ],
  },
  french: {
    male: [
      "Samuel",
      "Pierre",
      "Jean",
      "Jacques",
      "François",
      "Louis",
      "Charles",
      "Nicolas",
      "Guillaume",
      "Étienne",
      "Antoine",
      "Claude",
      "René",
      "Michel",
      "Mathieu",
      "Olivier",
    ],
    female: [
      "Marie",
      "Marguerite",
      "Anne",
      "Catherine",
      "Jeanne",
      "Hélène",
      "Madeleine",
      "Louise",
      "Geneviève",
      "Françoise",
      "Élisabeth",
      "Barbe",
    ],
    family: [
      "de Champlain",
      "du Gua",
      "Hébert",
      "Couillard",
      "Giffard",
      "Nicolet",
      "Brûlé",
      "Le Moyne",
      "de Maisonneuve",
      "Boucher",
      "Juchereau",
      "Godefroy",
      "Le Gardeur",
      "Denys",
      "d'Aulnay",
      "de La Tour",
    ],
  },
  spanish: {
    male: [
      "Juan",
      "Pedro",
      "Diego",
      "Francisco",
      "Alonso",
      "Luis",
      "Rodrigo",
      "Gonzalo",
      "Hernando",
      "Cristóbal",
      "Martín",
      "Andrés",
      "Gaspar",
      "Sebastián",
      "Lope",
      "Fadrique",
    ],
    female: [
      "María",
      "Isabel",
      "Juana",
      "Catalina",
      "Ana",
      "Inés",
      "Leonor",
      "Beatriz",
      "Francisca",
      "Luisa",
      "Mencía",
      "Elvira",
    ],
    family: [
      "de Valdés",
      "Méndez",
      "de Avilés",
      "de Canzo",
      "Ruiz",
      "de Oñate",
      "Pérez",
      "de Velasco",
      "de Guzmán",
      "Vázquez",
      "de Ibarra",
      "Osorio",
      "de Mendoza",
      "de Toledo",
      "Fajardo",
      "Quiñones",
    ],
  },
  portuguese: {
    male: [
      "João",
      "Pedro",
      "Diogo",
      "Francisco",
      "Afonso",
      "Luís",
      "Duarte",
      "Gonçalo",
      "Manuel",
      "Jerónimo",
      "Martim",
      "Vasco",
      "Fernão",
      "Salvador",
      "Bento",
      "Simão",
    ],
    female: [
      "Maria",
      "Isabel",
      "Joana",
      "Catarina",
      "Ana",
      "Inês",
      "Leonor",
      "Beatriz",
      "Brites",
      "Filipa",
      "Guiomar",
      "Mécia",
    ],
    family: [
      "de Sousa",
      "Coelho",
      "de Albuquerque",
      "Correia de Sá",
      "Vieira",
      "de Mello",
      "Cavalcanti",
      "Dias",
      "Barreto",
      "de Menezes",
      "Moniz",
      "Pereira",
      "Lobo",
      "Fernandes Vieira",
      "Telles",
      "de Castro",
    ],
  },
  dutch: {
    male: [
      "Pieter",
      "Jan",
      "Willem",
      "Cornelis",
      "Hendrick",
      "Adriaen",
      "Jacob",
      "Claes",
      "Dirck",
      "Gerrit",
      "Arent",
      "Wouter",
      "Joost",
      "Maarten",
      "Evert",
      "Reyer",
    ],
    female: [
      "Maria",
      "Anna",
      "Catalina",
      "Geertruyd",
      "Margriet",
      "Annetje",
      "Tryntje",
      "Sara",
      "Grietje",
      "Neeltje",
      "Aeltje",
      "Judith",
    ],
    family: [
      "Stuyvesant",
      "Minuit",
      "van Rensselaer",
      "Kieft",
      "van Twiller",
      "Block",
      "May",
      "Verhulst",
      "de Vries",
      "van der Donck",
      "Bogardus",
      "Krol",
      "Schuyler",
      "van Cortlandt",
      "Beeckman",
      "de Sille",
    ],
  },
  swedish: {
    male: [
      "Johan",
      "Peter",
      "Måns",
      "Nils",
      "Anders",
      "Olof",
      "Sven",
      "Lars",
      "Erik",
      "Hans",
      "Carl",
      "Gustaf",
      "Mårten",
      "Jöns",
      "Per",
      "Lasse",
    ],
    female: [
      "Maria",
      "Kristina",
      "Brita",
      "Karin",
      "Anna",
      "Margareta",
      "Elin",
      "Ingrid",
      "Ebba",
      "Kerstin",
      "Sigrid",
      "Märta",
    ],
    family: [
      "Printz",
      "Rising",
      "Minuit",
      "Kling",
      "Lindeström",
      "Papegoja",
      "Huygen",
      "Bengtsson",
      "Rambo",
      "Cock",
      "Svensson",
      "Stidden",
      "Mattsson",
      "Wheeler",
      "Dalbo",
      "Jönsson",
    ],
  },
};

/** What each native nation called its leader (or the nearest common word). */
export const NATIVE_TITLES: Record<string, string> = {
  powhatan: "Mamanatowick",
  haudenosaunee: "Tadodaho",
  wendat: "Head chief",
  wampanoag: "Massasoit",
  narragansett: "Sachem",
  mexica: "Tlatoani",
  purepecha: "Irecha",
  inca: "Sapa Inca",
  maya: "Halach uinic",
  itza: "Ajaw",
  kiche: "Ajpop",
  mapuche: "Toqui",
  muisca: "Zipa",
  muscogee: "Mico",
  cherokee: "Uku",
  choctaw: "Mingo",
  chickasaw: "Minko",
  natchez: "Great Sun",
  timucua: "Holata",
};

export function nativeTitle(key: string): string {
  return NATIVE_TITLES[key] ?? "Chief";
}
