// Where everyone stands at each start date. 1607 is the map's own; 1650 and
// 1700 follow history for the English, French, Dutch and Swedish colonies,
// grow Spain modestly from the 1607 baseline, and take land from native
// nations that had been destroyed or scattered by then.
//
// Owners and development are by province name; Setup maps them onto the map.

import type { StartYear } from "./Types";

export interface StartDef {
  year: StartYear;
  /** Two or three sentences for the start-date picker. */
  summary: string;
  /** Each owned province: nation key. Unlisted provinces are open country. */
  owners: Record<string, string>;
  capitals: Record<string, string>;
  /** Nations with no land in this year. */
  gone: string[];
  /** Colony provinces: 1 a fledgling settlement, 2 a town, 3 thriving, 4 a city. */
  development: Record<string, number>;
  /** A sentence or two per colony for the nation-pick screen. */
  powerNotes: Record<string, string>;
}

export const START_YEARS: StartYear[] = [1607, 1650, 1700];

export const START_SUMMARY_1607 =
  "Jamestown has just been founded, Champlain is about to plant Quebec, and Spain guards the Caribbean alone. Most of the continent belongs to its native nations.";

/** Settlers in a colony province of each development level. */
export const DEVELOPMENT_SETTLERS = [0, 250, 900, 2400, 4800];

/** Gold in the treasury, as a multiple of the 1607 amount. */
export const START_GOLD_FACTOR: Record<StartYear, number> = {
  1607: 1,
  1650: 2,
  1700: 3.2,
};

export const STARTS: Partial<Record<StartYear, StartDef>> = {
  1650: {
    year: 1650,
    summary:
      "Spain still holds the Caribbean's great ports, but English and French settlers now crowd the Atlantic coast and the Lesser Antilles. The Iroquois have just destroyed the Wendat and are carrying the Beaver Wars across the Great Lakes, while New Netherland and New Sweden cling to the Hudson and the Delaware.",
    owners: {
      Avalon: "england",
      Piscataqua: "england",
      Sagadahoc: "england",
      "Massachusetts Bay": "england",
      Plymouth: "england",
      Connecticut: "england",
      Pequot: "england",
      Paumanok: "england",
      Jamestown: "england",
      Pamunkey: "england",
      Appamattuck: "england",
      Nansemond: "england",
      Accomac: "england",
      Rappahannock: "england",
      "St. Mary's": "england",
      Severn: "england",
      Zwaanendael: "england",
      Bermuda: "england",
      "New Providence": "england",
      "St. Kitts": "england",
      Antigua: "england",
      Barbados: "england",
      Quebec: "france",
      Tadoussac: "france",
      "Trois-Rivières": "france",
      Hochelaga: "france",
      "Port-Royal": "france",
      "La Hève": "france",
      "Saint-Jean": "france",
      "Le Cap": "france",
      Martinique: "france",
      Guadeloupe: "france",
      Grenada: "france",
      "St. Augustine": "spain",
      Timucua: "spain",
      Apalachee: "spain",
      Guale: "spain",
      Havana: "spain",
      "Vuelta Abajo": "spain",
      "Sancti Spíritus": "spain",
      "Puerto Príncipe": "spain",
      Bayamo: "spain",
      "Santiago de Cuba": "spain",
      "Santo Domingo": "spain",
      Higüey: "spain",
      Cibao: "spain",
      "San Juan": "spain",
      Jamaica: "spain",
      Veracruz: "spain",
      Campeche: "spain",
      Panama: "spain",
      Portobelo: "spain",
      "New Amsterdam": "netherlands",
      "Fort Orange": "netherlands",
      Curaçao: "netherlands",
      // WORLD r11: the Dutch took Aruba and Bonaire with Curaçao in 1636.
      Aruba: "netherlands",
      Bonaire: "netherlands",
      "St. Thomas": "netherlands",
      "Fort Christina": "sweden",
      Upland: "sweden",
      Saguenay: "innu",
      "Sept-Îles": "innu",
      Mishikamau: "innu",
      Kituwah: "cherokee",
      Chota: "cherokee",
      Etowah: "cherokee",
      Keowee: "cherokee",
      Ocmulgee: "muscogee",
      Coweta: "muscogee",
      Tallapoosa: "muscogee",
      Coosa: "muscogee",
      Chickasaw: "chickasaw",
      "Muscle Shoals": "chickasaw",
      Calusa: "calusa",
      Mayaimi: "calusa",
      Tequesta: "calusa",
      Natchez: "natchez",
      Tunica: "natchez",
      Kadohadacho: "caddo",
      Hasinai: "caddo",
      Cahokia: "illinois",
      Peoria: "illinois",
      Osage: "osage",
      Kansa: "osage",
      "Mde Wakan": "oceti",
      Lakota: "oceti",
      Yanktonai: "oceti",
      "Black Hills": "oceti",
      Pawnee: "pawnee",
      Platte: "pawnee",
      Gila: "apache",
      Mescalero: "apache",
      "Llano Estacado": "apache",
      Taos: "pueblo",
      Acoma: "pueblo",
      Zuni: "pueblo",
      Hopi: "pueblo",
      Diné: "dine",
      "Snake River": "shoshone",
      "Wind River": "shoshone",
      Blackfoot: "blackfoot",
      Mohkinstsis: "blackfoot",
      Chumash: "chumash",
      Tongva: "chumash",
      "Puget Sound": "salish",
      Lekwungen: "salish",
      "Stó:lō": "salish",
      Tahltan: "tlingit",
      Tenochtitlan: "mexica",
      Pachuca: "mexica",
      Taxco: "mexica",
      Tlaxcala: "mexica",
      Michoacán: "purepecha",
      Colima: "purepecha",
      Zacatecas: "chichimeca",
      "San Luis Potosí": "chichimeca",
      Guanajuato: "chichimeca",
      Oaxaca: "zapotec",
      Tehuantepec: "zapotec",
      Mixteca: "zapotec",
      "T'Hó": "maya",
      Tulum: "maya",
      "Petén Itzá": "itza",
      Bacalar: "itza",
      "Santiago de Guatemala": "kiche",
      Verapaz: "kiche",
      "Mosquito Coast": "miskito",
      Bluefields: "miskito",
      Dominica: "kalinago",
      "St. Vincent": "kalinago",
      Mohawk: "haudenosaunee",
      Oneida: "haudenosaunee",
      Onondaga: "haudenosaunee",
      Seneca: "haudenosaunee",
      Attawandaron: "attawandaron",
      Niagara: "attawandaron",
      Erie: "erie",
      Allegheny: "erie",
      Susquehannock: "susquehannock",
      Shamokin: "susquehannock",
      Raritan: "lenape",
      Minisink: "lenape",
      Pentagoet: "wabanaki",
      Norridgewock: "wabanaki",
      Madawaska: "wabanaki",
      Miramichi: "mikmaq",
      Chebucto: "mikmaq",
      "Île Saint-Jean": "mikmaq",
      "Île Royale": "mikmaq",
      Narragansett: "narragansett",
      Bawating: "anishinaabe",
      Odawa: "anishinaabe",
      Chequamegon: "anishinaabe",
      Michilimackinac: "anishinaabe",
      "Moose River": "cree",
      "Fort Albany": "cree",
      Missinaibi: "cree",
      Choctaw: "choctaw",
      Mobile: "choctaw",
    },
    capitals: {
      england: "Jamestown",
      france: "Quebec",
      spain: "Havana",
      netherlands: "New Amsterdam",
      sweden: "Fort Christina",
    },
    gone: ["powhatan", "wendat", "wampanoag", "timucua"],
    development: {
      Avalon: 1,
      Piscataqua: 2,
      Sagadahoc: 1,
      "Massachusetts Bay": 3,
      Plymouth: 2,
      Connecticut: 2,
      Pequot: 1,
      Paumanok: 1,
      Jamestown: 3,
      Pamunkey: 1,
      Appamattuck: 1,
      Nansemond: 2,
      Accomac: 2,
      Rappahannock: 1,
      "St. Mary's": 2,
      Severn: 1,
      Zwaanendael: 1,
      Bermuda: 2,
      "New Providence": 1,
      "St. Kitts": 2,
      Antigua: 1,
      Barbados: 3,
      Quebec: 2,
      Tadoussac: 1,
      "Trois-Rivières": 1,
      Hochelaga: 1,
      "Port-Royal": 1,
      "La Hève": 1,
      "Saint-Jean": 1,
      "Le Cap": 1,
      Martinique: 2,
      Guadeloupe: 2,
      Grenada: 1,
      "St. Augustine": 2,
      Timucua: 1,
      Apalachee: 1,
      Guale: 1,
      Havana: 4,
      "Vuelta Abajo": 1,
      "Sancti Spíritus": 1,
      "Puerto Príncipe": 2,
      Bayamo: 2,
      "Santiago de Cuba": 2,
      "Santo Domingo": 3,
      Higüey: 1,
      Cibao: 2,
      "San Juan": 2,
      Jamaica: 1,
      Veracruz: 2,
      Campeche: 2,
      Panama: 3,
      Portobelo: 2,
      "New Amsterdam": 2,
      "Fort Orange": 1,
      Curaçao: 1,
      Aruba: 1,
      Bonaire: 1,
      "St. Thomas": 1,
      "Fort Christina": 1,
      Upland: 1,
    },
    powerNotes: {
      england:
        "England is now the leading colonial power on the mainland: Virginia and Maryland plant tobacco on land taken from the broken Powhatan, Puritan New England runs from Long Island to the Kennebec, and Barbados is turning to sugar. With the king just executed and Parliament at war, the colonies largely govern themselves.",
      france:
        "New France is under a thousand settlers at Quebec, Trois-Rivières and Ville-Marie, harried by Iroquois war parties now that the Wendat allies have been scattered. Acadia is a few posts around Port-Royal, but Martinique and Guadeloupe prosper, Grenada was settled last year, and Tortuga's buccaneers fly the French flag.",
      spain:
        "Spain holds the strongest ports in the Caribbean: Havana gathers the treasure fleets, and Spanish Cuba, Hispaniola, Puerto Rico and Jamaica ring the sea, while Franciscan missions run from St. Augustine to Apalachee. Its mainland footholds at Veracruz, Campeche, Panama and Portobelo are rich but surrounded by unconquered nations.",
      netherlands:
        "Director Stuyvesant rules New Netherland's fur trade from New Amsterdam up the Hudson to Fort Orange, while Curaçao and Tortola anchor the West India Company's Caribbean trade. English New England presses hard on every border.",
      sweden:
        "New Sweden is a few hundred Swedes and Finns on the Delaware under Governor Johan Printz, trading for furs with the Lenape and Susquehannock. The Dutch share the river and supply ships from Stockholm are rare.",
    },
  },
  1700: {
    year: 1700,
    summary:
      "England's colonies run unbroken from New Hampshire to Carolina, New France stretches from the St. Lawrence to the new post at Biloxi, and Spain is fortifying Florida and the Gulf against both. Fifty years of war have destroyed the Erie, the Neutral, the Susquehannock and the Narragansett, and a dying Spanish king threatens a new war.",
    owners: {
      Avalon: "england",
      Piscataqua: "england",
      "Massachusetts Bay": "england",
      Plymouth: "england",
      Narragansett: "england",
      Connecticut: "england",
      Pequot: "england",
      Pocumtuck: "england",
      Paumanok: "england",
      "New Amsterdam": "england",
      "Fort Orange": "england",
      Esopus: "england",
      Raritan: "england",
      "Fort Christina": "england",
      Upland: "england",
      Zwaanendael: "england",
      Jamestown: "england",
      Pamunkey: "england",
      Appamattuck: "england",
      Nansemond: "england",
      Accomac: "england",
      Rappahannock: "england",
      "St. Mary's": "england",
      Severn: "england",
      Piscataway: "england",
      Albemarle: "england",
      "Charles Town": "england",
      "Fort Albany": "england",
      Bermuda: "england",
      "New Providence": "england",
      Jamaica: "england",
      "St. Kitts": "england",
      Antigua: "england",
      Barbados: "england",
      Quebec: "france",
      Tadoussac: "france",
      "Trois-Rivières": "france",
      Hochelaga: "france",
      Champlain: "france",
      Cataraqui: "france",
      Placentia: "france",
      "Port-Royal": "france",
      "La Hève": "france",
      "Saint-Jean": "france",
      Beaubassin: "france",
      Chebucto: "france",
      "York Factory": "france",
      Mobile: "france",
      "Le Cap": "france",
      Léogâne: "france",
      Tiburon: "france",
      Martinique: "france",
      Guadeloupe: "france",
      Grenada: "france",
      "St. Augustine": "spain",
      Timucua: "spain",
      Apalachee: "spain",
      Pensacola: "spain",
      Havana: "spain",
      "Vuelta Abajo": "spain",
      "Sancti Spíritus": "spain",
      "Puerto Príncipe": "spain",
      Bayamo: "spain",
      "Santiago de Cuba": "spain",
      "Santo Domingo": "spain",
      Higüey: "spain",
      Cibao: "spain",
      "San Juan": "spain",
      Veracruz: "spain",
      Campeche: "spain",
      Panama: "spain",
      Portobelo: "spain",
      Curaçao: "netherlands",
      // WORLD r11: the Dutch took Aruba and Bonaire with Curaçao in 1636.
      Aruba: "netherlands",
      Bonaire: "netherlands",
      "St. Thomas": "netherlands",
      Saguenay: "innu",
      "Sept-Îles": "innu",
      Mishikamau: "innu",
      Kituwah: "cherokee",
      Chota: "cherokee",
      Etowah: "cherokee",
      Keowee: "cherokee",
      Ocmulgee: "muscogee",
      Coweta: "muscogee",
      Tallapoosa: "muscogee",
      Coosa: "muscogee",
      Chickasaw: "chickasaw",
      "Muscle Shoals": "chickasaw",
      Calusa: "calusa",
      Mayaimi: "calusa",
      Tequesta: "calusa",
      Natchez: "natchez",
      Tunica: "natchez",
      Kadohadacho: "caddo",
      Hasinai: "caddo",
      Cahokia: "illinois",
      Peoria: "illinois",
      Osage: "osage",
      Kansa: "osage",
      "Mde Wakan": "oceti",
      Lakota: "oceti",
      Yanktonai: "oceti",
      "Black Hills": "oceti",
      Pawnee: "pawnee",
      Platte: "pawnee",
      Gila: "apache",
      Mescalero: "apache",
      "Llano Estacado": "apache",
      Taos: "pueblo",
      Acoma: "pueblo",
      Zuni: "pueblo",
      Hopi: "pueblo",
      Diné: "dine",
      "Snake River": "shoshone",
      "Wind River": "shoshone",
      Blackfoot: "blackfoot",
      Mohkinstsis: "blackfoot",
      Chumash: "chumash",
      Tongva: "chumash",
      "Puget Sound": "salish",
      Lekwungen: "salish",
      "Stó:lō": "salish",
      Tahltan: "tlingit",
      Tenochtitlan: "mexica",
      Pachuca: "mexica",
      Taxco: "mexica",
      Tlaxcala: "mexica",
      Michoacán: "purepecha",
      Colima: "purepecha",
      Zacatecas: "chichimeca",
      "San Luis Potosí": "chichimeca",
      Guanajuato: "chichimeca",
      Oaxaca: "zapotec",
      Tehuantepec: "zapotec",
      Mixteca: "zapotec",
      "T'Hó": "maya",
      Tulum: "maya",
      "Petén Itzá": "itza",
      Bacalar: "itza",
      "Santiago de Guatemala": "kiche",
      Verapaz: "kiche",
      "Mosquito Coast": "miskito",
      Bluefields: "miskito",
      Dominica: "kalinago",
      "St. Vincent": "kalinago",
      Mohawk: "haudenosaunee",
      Oneida: "haudenosaunee",
      Onondaga: "haudenosaunee",
      Seneca: "haudenosaunee",
      Niagara: "haudenosaunee",
      Minisink: "lenape",
      Pentagoet: "wabanaki",
      Norridgewock: "wabanaki",
      Madawaska: "wabanaki",
      Sagadahoc: "wabanaki",
      Miramichi: "mikmaq",
      "Île Saint-Jean": "mikmaq",
      "Île Royale": "mikmaq",
      Bawating: "anishinaabe",
      Odawa: "anishinaabe",
      Chequamegon: "anishinaabe",
      Michilimackinac: "anishinaabe",
      Wendake: "anishinaabe",
      Teiaiagon: "anishinaabe",
      "Moose River": "cree",
      Missinaibi: "cree",
      Choctaw: "choctaw",
    },
    capitals: {
      england: "Jamestown",
      france: "Quebec",
      spain: "Havana",
      netherlands: "Curaçao",
    },
    gone: [
      "sweden",
      "powhatan",
      "wendat",
      "attawandaron",
      "erie",
      "susquehannock",
      "wampanoag",
      "narragansett",
      "timucua",
    ],
    development: {
      Avalon: 1,
      Piscataqua: 2,
      "Massachusetts Bay": 4,
      Plymouth: 2,
      Narragansett: 2,
      Connecticut: 3,
      Pequot: 2,
      Pocumtuck: 1,
      Paumanok: 2,
      "New Amsterdam": 3,
      "Fort Orange": 2,
      Esopus: 1,
      Raritan: 2,
      "Fort Christina": 3,
      Upland: 1,
      Zwaanendael: 2,
      Jamestown: 3,
      Pamunkey: 2,
      Appamattuck: 2,
      Nansemond: 2,
      Accomac: 2,
      Rappahannock: 2,
      "St. Mary's": 2,
      Severn: 2,
      Piscataway: 1,
      Albemarle: 1,
      "Charles Town": 2,
      "Fort Albany": 1,
      Bermuda: 2,
      "New Providence": 1,
      Jamaica: 3,
      "St. Kitts": 2,
      Antigua: 2,
      Barbados: 4,
      Quebec: 3,
      Tadoussac: 1,
      "Trois-Rivières": 2,
      Hochelaga: 2,
      Champlain: 1,
      Cataraqui: 1,
      Placentia: 1,
      "Port-Royal": 2,
      "La Hève": 1,
      "Saint-Jean": 1,
      Beaubassin: 1,
      Chebucto: 2,
      "York Factory": 1,
      Mobile: 1,
      "Le Cap": 2,
      Léogâne: 2,
      Tiburon: 1,
      Martinique: 3,
      Guadeloupe: 2,
      Grenada: 1,
      "St. Augustine": 2,
      Timucua: 1,
      Apalachee: 2,
      Pensacola: 1,
      Havana: 4,
      "Vuelta Abajo": 1,
      "Sancti Spíritus": 2,
      "Puerto Príncipe": 2,
      Bayamo: 2,
      "Santiago de Cuba": 2,
      "Santo Domingo": 2,
      Higüey: 1,
      Cibao: 2,
      "San Juan": 2,
      Veracruz: 2,
      Campeche: 2,
      Panama: 3,
      Portobelo: 2,
      Curaçao: 3,
      Aruba: 1,
      Bonaire: 1,
      "St. Thomas": 2,
    },
    powerNotes: {
      england:
        "England's colonies now run unbroken from New Hampshire to Carolina, with New York taken from the Dutch, Pennsylvania and the Jerseys founded, and Jamaica and Barbados leading a sugar empire. Boston, New York and Philadelphia are busy ports, though the Maine frontier has just been lost to the Wabanaki and Fort Albany is the last English post on Hudson Bay.",
      france:
        "New France has about 15,000 settlers along the St. Lawrence, holds Fort Frontenac on Lake Ontario, and planted Louisiana at Biloxi last spring. Acadia, Plaisance in Newfoundland, York Factory on Hudson Bay and the new sugar colony of Saint-Domingue complete a scattered but ambitious empire.",
      spain:
        "Spain has lost Jamaica to England and western Hispaniola to France, and Carolina's raiders have driven its missions out of Guale. It still holds Havana, the richest port in the Americas, and has just fortified Pensacola against the French, while the childless Charles II lies dying.",
      netherlands:
        "Since losing New Netherland to England, the Dutch live by trade rather than settlement: Curaçao is the Caribbean's great slave and smuggling market, and Dutch merchants and planters dominate the Virgin Islands under a foreign flag.",
    },
  },
};
