// Who made the art, sounds and music in Derpy Conquest, and under what
// licence. Shown in the game's menu and on the lobby page. CC-BY works need
// their author named; the rest are public domain or CC0 but credited anyway.

import { html, TemplateResult } from "lit";

export interface Credit {
  what: string;
  title: string;
  author: string;
  license: string;
  source: string;
}

export const CREDITS: Credit[] = [
  {
    what: "Picture",
    title: "Galleon",
    author: "papapishu",
    license: "CC0",
    source: "https://openclipart.org/detail/22696/galleon",
  },
  {
    what: "Picture",
    title: "Galleon ship silhouette",
    author: "GDJ",
    license: "CC0",
    source: "https://openclipart.org/detail/287955/galleon-ship-silhouette",
  },
  {
    what: "Picture",
    title: "Canoe silhouette",
    author: "johnny_automatic",
    license: "CC0",
    source: "https://openclipart.org/detail/377/canoe-silhouette",
  },
  {
    what: "Picture",
    title: "Musketman",
    author: "Technopeasant",
    license: "CC0",
    source: "https://openclipart.org/detail/342427/musketman",
  },
  {
    what: "Picture",
    title: "Musketman aiming",
    author: "Technopeasant",
    license: "CC0",
    source: "https://openclipart.org/detail/342428/musketman-aiming",
  },
  {
    what: "Picture",
    title: "Musketeer surveying",
    author: "Technopeasant",
    license: "CC0",
    source: "https://openclipart.org/detail/342536/musketeer-surveying",
  },
  {
    what: "Picture",
    title: "Horseman",
    author: "matzekatze",
    license: "CC0",
    source: "https://openclipart.org/detail/174948/horseman",
  },
  {
    what: "Picture",
    title: "Medieval cannon",
    author: "Helm42",
    license: "CC0",
    source: "https://openclipart.org/detail/169260/medieval-cannon",
  },
  {
    what: "Picture",
    title:
      "John White - An Indian 'werowance', or chief, painted for a great solemn gathering, 1906,0509.1.12",
    author: "John White (watercolour, c.1585-1593)",
    license: "Public Domain",
    source:
      "https://commons.wikimedia.org/wiki/File:John_White_-_An_Indian_'werowance',_or_chief,_painted_for_a_great_solemn_gathering,_1906,0509.1.12.jpg",
  },
  {
    what: "Picture",
    title: "John White - The town of Pomeiooc, 1906,0509.1.8",
    author: "John White (watercolour, c.1585-1593)",
    license: "Public Domain",
    source:
      "https://commons.wikimedia.org/wiki/File:John_White_-_The_town_of_Pomeiooc,_1906,0509.1.8.jpg",
  },
  {
    what: "Picture",
    title: "RPG map symbols: fort 2 (sepia map style)",
    author: "Nicu Buculei (nicubunu)",
    license: "CC0",
    source: "https://openclipart.org/detail/11451/rpg-map-symbols-fort-2",
  },
  {
    what: "Picture",
    title: "RPG map symbols: village 2 (sepia)",
    author: "Nicu Buculei (nicubunu)",
    license: "CC0",
    source: "https://openclipart.org/detail/11544/rpg-map-symbols-village-2",
  },
  {
    what: "Picture",
    title: "RPG map symbols: city 2 (sepia)",
    author: "Nicu Buculei (nicubunu)",
    license: "CC0",
    source: "https://openclipart.org/detail/11439/rpg-map-symbols-city-2",
  },
  {
    what: "Picture",
    title: "RPG map symbols: warehouse/docks (sepia)",
    author: "Nicu Buculei (nicubunu)",
    license: "CC0",
    source: "https://openclipart.org/detail/11511",
  },
  {
    what: "Texture",
    title: "Paper006 (ambientCG paper material, Color map)",
    author: "ambientCG (Lennart Demes)",
    license: "CC0",
    source: "https://ambientcg.com/view?id=Paper006",
  },
  {
    what: "Texture",
    title: "Engraved sea wave hatching (seamless overlay, ink on transparent)",
    author: "Generated for Derpy Conquest",
    license: "CC0",
    source: "generated by script (no external source)",
  },
  {
    what: "Texture",
    title: "Hachured molehill hills (seamless overlay)",
    author: "Generated for Derpy Conquest",
    license: "CC0",
    source: "generated by script (no external source)",
  },
  {
    what: "Texture",
    title: "Hachured sugar-loaf mountains (seamless overlay)",
    author: "Generated for Derpy Conquest",
    license: "CC0",
    source: "generated by script (no external source)",
  },
  {
    what: "Texture",
    title:
      "Forest pictogram pattern built from game-icons 'pine-tree' and 'oak'",
    author: "Lorc (game-icons.net)",
    license: "CC BY 3.0",
    source:
      "https://game-icons.net/1x1/lorc/pine-tree.html ; https://game-icons.net/1x1/lorc/oak.html",
  },
  {
    what: "Texture",
    title:
      "Marsh pictogram pattern built from game-icons 'reed' and 'high-grass'",
    author: "Delapouite (game-icons.net)",
    license: "CC BY 3.0",
    source:
      "https://game-icons.net/1x1/delapouite/reed.html ; https://game-icons.net/1x1/delapouite/high-grass.html",
  },
  {
    what: "Sound",
    title: "Cannon fire",
    author: "Thimras (OpenGameArt)",
    license: "CC0",
    source: "https://opengameart.org/content/cannon-fire",
  },
  {
    what: "Sound",
    title: "Musket Fire (Minute Man National Historical Park)",
    author: "U.S. National Park Service (NPS Natural Sounds)",
    license: "Public domain",
    source: "https://www.nps.gov/subjects/sound/sounds-musket.htm",
  },
  {
    what: "Sound",
    title: "Battle Sounds (Cedar Creek reenactment)",
    author: "U.S. National Park Service (NPS Natural Sounds)",
    license: "Public domain",
    source: "https://www.nps.gov/subjects/sound/sounds-battle.htm",
  },
  {
    what: "Sound",
    title: "Drum Feature: Generations (excerpt)",
    author: "The United States Army Old Guard Fife and Drum Corps",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_United_States_Army_Old_Guard_Fife_and_Drum_Corps_-_16_-_Drum_Feature_Generations_from_the_Simple_Gifts_Show.ogg",
  },
  {
    what: "Sound",
    title:
      "WWS Signalbell (Funke & Huster signal bell, LWL-Industriemuseum Zeche Zollern)",
    author: "Work With Sounds / Konrad Gutkowski",
    license: "CC BY 4.0",
    source: "https://commons.wikimedia.org/wiki/File:WWS_Signalbell.ogg",
  },
  {
    what: "Sound",
    title: "Pencil Sounds (pencil_write)",
    author: "AntumDeluge (Jordan Irwin)",
    license: "CC0",
    source: "https://opengameart.org/content/pencil-sounds",
  },
  {
    what: "Sound",
    title: "Impact Sounds",
    author: "Kenney (www.kenney.nl)",
    license: "CC0",
    source: "https://kenney.nl/assets/impact-sounds",
  },
  {
    what: "Sound",
    title: "Pirate Pack Vol 1",
    author: "JC Sounds",
    license: "CC BY 4.0",
    source: "https://opengameart.org/content/jc-sounds-pirate-pack-vol-1",
  },
  {
    what: "Sound",
    title: "RPG Audio",
    author: "Kenney (www.kenney.nl)",
    license: "CC0",
    source: "https://kenney.nl/assets/rpg-audio",
  },
  {
    what: "Sound",
    title: "Monteverdi: Toccata from L'Orfeo (1607), opening",
    author: "The United States Army Old Guard Fife and Drum Corps",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_United_States_Army_Old_Guard_Fife_and_Drum_Corps_-_20_-_Monteverdis_Toccata_from_LOrfeo.ogg",
  },
  {
    what: "Sound",
    title: "ERAFNAF Fanfare (opening)",
    author: "The United States Army Old Guard Fife and Drum Corps",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_United_States_Army_Old_Guard_Fife_and_Drum_Corps_-_01_-_ERAFNAF_Fanfare.ogg",
  },
  {
    what: "Sound",
    title: "Classic fanfare lick",
    author: "fvcalderan",
    license: "CC0",
    source: "https://opengameart.org/content/classic-fanfare-lick",
  },
  {
    what: "Music",
    title: "Suonatore di Liuto",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1400023",
  },
  {
    what: "Music",
    title: "Teller of the Tales",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1400020",
  },
  {
    what: "Music",
    title: "Village Consort",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1700007",
  },
  {
    what: "Music",
    title: "Sinfonia Number 5",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100673",
  },
  {
    what: "Music",
    title: "Monteverdi: Toccata from L'Orfeo (1607)",
    author: "The United States Army Old Guard Fife and Drum Corps",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_United_States_Army_Old_Guard_Fife_and_Drum_Corps_-_20_-_Monteverdis_Toccata_from_LOrfeo.ogg",
  },
  {
    what: "Music",
    title: "Bugle Feature: Pezel Twist (from Warlike Musick)",
    author: "The United States Army Old Guard Fife and Drum Corps",
    license: "CC0",
    source:
      "https://commons.wikimedia.org/wiki/File:The_United_States_Army_Old_Guard_Fife_and_Drum_Corps_-_08_-_Bugle_Feature_Pezel_Twist_from_Warlike_Musick.ogg",
  },
  {
    what: "Music",
    title: "Achaidh Cheide",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100340",
  },
  {
    what: "Music",
    title: "Fife and Drum",
    author: "Kevin MacLeod (incompetech.com)",
    license: "CC BY 4.0",
    source:
      "https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1600025",
  },
];

const GROUPS: [Credit["what"], string][] = [
  ["Music", "Music"],
  ["Sound", "Sounds"],
  ["Picture", "Pictures"],
  ["Texture", "Textures"],
];

/** The credits, grouped, with links to where each came from. */
export function creditsList(): TemplateResult {
  return html`<div class="cq-credits">
    ${GROUPS.map(
      ([what, title]) =>
        html`<section>
          <h3 class="cq-h3">${title}</h3>
          <ul>
            ${CREDITS.filter((c) => c.what === what).map(
              (c) =>
                html`<li>
                  <a href=${c.source} target="_blank" rel="noopener"
                    >${c.title}</a
                  >
                  ${c.author.startsWith("Generated")
                    ? "(made for Derpy Conquest)"
                    : `by ${c.author}`}
                  <span class="cq-muted small">(${c.license})</span>
                </li>`,
            )}
          </ul>
        </section>`,
    )}
  </div>`;
}
